DECLARE @key_table TABLE (num int, data varchar(7), length int);

INSERT INTO @key_table VALUES
(0, 'abcefg', LEN('abcefg')), 
(1, 'cf', LEN('cf')),
(2, 'acdeg', LEN('acdeg')),
(3, 'acdfg', LEN('acdfg')),
(4, 'bcdf', LEN('bcdf')),
(5, 'abdfg', LEN('abdfg')),
(6, 'abdefg', LEN('abdefg')),
(7, 'acf', LEN('acf')),
(8, 'abcdefg', LEN('abcdefg'))

DECLARE @input TABLE (id int, data varchar(7), length int)
DECLARE @output TABLE (id int, data varchar(7), length int)

INSERT INTO @input VALUES
 (1, 'aedcg', LEN('aedcg')), (1, 'db', LEN('db')), (1, 'ecbdgf', LEN('ecbdgf')), (1, 'badfegc', LEN('badfegc')), (1, 'abfcde', LEN('abfcde')), (1, 'edb', LEN('edb')), (1, 'cbgfe', LEN('cbgfe')), (1, 'bfdg', LEN('bfdg')), (1, 'bdgec', LEN('bdgec')), (1, 'agfbce', LEN('agfbce')),
 (2, 'bgeadf', LEN('bgeadf')), (2, 'egcbda', LEN('egcbda')), (2, 'cfebg', LEN('cfebg')), (2, 'ac', LEN('ac')), (2, 'caefbdg', LEN('caefbdg')), (2, 'bacd', LEN('bacd')), (2, 'ecfgad', LEN('ecfgad')), (2, 'cabeg', LEN('cabeg')), (2, 'gca', LEN('gca')), (2, 'abgde', LEN('abgde')),
 (3, 'cbfge', LEN('cbfge')), (3, 'ed', LEN('ed')), (3, 'aegbcd', LEN('aegbcd')), (3, 'gfdba', LEN('gfdba')), (3, 'aedf', LEN('aedf')), (3, 'facbdge', LEN('facbdge')), (3, 'fdegba', LEN('fdegba')), (3, 'bfgcda', LEN('bfgcda')), (3, 'befdg', LEN('befdg')), (3, 'dge', LEN('dge')),
 (4, 'efdga', LEN('efdga')), (4, 'dgebfc', LEN('dgebfc')), (4, 'cefa', LEN('cefa')), (4, 'edgfc', LEN('edgfc')), (4, 'decbagf', LEN('decbagf')), (4, 'cdagfe', LEN('cdagfe')), (4, 'ade', LEN('ade')), (4, 'bgafd', LEN('bgafd')), (4, 'ae', LEN('ae')), (4, 'cadbge', LEN('cadbge')),
 (5, 'fe', LEN('fe')), (5, 'bdcge', LEN('bdcge')), (5, 'ecfbdg', LEN('ecfbdg')), (5, 'ecf', LEN('ecf')), (5, 'bdfe', LEN('bdfe')), (5, 'gdacbe', LEN('gdacbe')), (5, 'gdefcab', LEN('gdefcab')), (5, 'gfcad', LEN('gfcad')), (5, 'cdgef', LEN('cdgef')), (5, 'ceagbf', LEN('ceagbf')),
 (6, 'gfacedb', LEN('gfacedb')), (6, 'bfgadc', LEN('bfgadc')), (6, 'fbdgec', LEN('fbdgec')), (6, 'eagcb', LEN('eagcb')), (6, 'cdfe', LEN('cdfe')), (6, 'cd', LEN('cd')), (6, 'gcd', LEN('gcd')), (6, 'afedbg', LEN('afedbg')), (6, 'bdceg', LEN('bdceg')), (6, 'gfdeb', LEN('gfdeb')),
 (7, 'bfecadg', LEN('bfecadg')), (7, 'fdbage', LEN('fdbage')), (7, 'bdgfca', LEN('bdgfca')), (7, 'cfba', LEN('cfba')), (7, 'fdceg', LEN('fdceg')), (7, 'acdgeb', LEN('acdgeb')), (7, 'dfa', LEN('dfa')), (7, 'af', LEN('af')), (7, 'acgbd', LEN('acgbd')), (7, 'gadcf', LEN('gadcf')),
 (8, 'fbaeg', LEN('fbaeg')), (8, 'dbcegf', LEN('dbcegf')), (8, 'acgfbd', LEN('acgfbd')), (8, 'gadbecf', LEN('gadbecf')), (8, 'bfagce', LEN('bfagce')), (8, 'ge', LEN('ge')), (8, 'bedfa', LEN('bedfa')), (8, 'bfagc', LEN('bfagc')), (8, 'cage', LEN('cage')), (8, 'efg', LEN('efg')),
 (9, 'bcad', LEN('bcad')), (9, 'gcefbad', LEN('gcefbad')), (9, 'afbdg', LEN('afbdg')), (9, 'cgfea', LEN('cgfea')), (9, 'gfedba', LEN('gfedba')), (9, 'dcbegf', LEN('dcbegf')), (9, 'dagbfc', LEN('dagbfc')), (9, 'gfcab', LEN('gfcab')), (9, 'cb', LEN('cb')), (9, 'gcb', LEN('gcb')),
 (10, 'eabgcd', LEN('eabgcd')), (10, 'eagfbd', LEN('eagfbd')), (10, 'fdgb', LEN('fdgb')), (10, 'gbdea', LEN('gbdea')), (10, 'dbaecgf', LEN('dbaecgf')), (10, 'fbe', LEN('fbe')), (10, 'bf', LEN('bf')), (10, 'fdcbea', LEN('fdcbea')), (10, 'gfeba', LEN('gfeba')), (10, 'faegc', LEN('faegc')),
 (11, 'cf', LEN('cf')), (11, 'fabdg', LEN('fabdg')), (11, 'fbeagc', LEN('fbeagc')), (11, 'gefc', LEN('gefc')), (11, 'bfc', LEN('bfc')), (11, 'caegb', LEN('caegb')), (11, 'gbeacd', LEN('gbeacd')), (11, 'cgafb', LEN('cgafb')), (11, 'cadbfe', LEN('cadbfe')), (11, 'fagdecb', LEN('fagdecb')),
 (12, 'acdgb', LEN('acdgb')), (12, 'gbcfe', LEN('gbcfe')), (12, 'fbdecga', LEN('fbdecga')), (12, 'df', LEN('df')), (12, 'cgafed', LEN('cgafed')), (12, 'efbagc', LEN('efbagc')), (12, 'bcgdf', LEN('bcgdf')), (12, 'dfgcbe', LEN('dfgcbe')), (12, 'fgd', LEN('fgd')), (12, 'fbed', LEN('fbed')),
 (13, 'fc', LEN('fc')), (13, 'cebad', LEN('cebad')), (13, 'fdagb', LEN('fdagb')), (13, 'fbc', LEN('fbc')), (13, 'gbfade', LEN('gbfade')), (13, 'dcfgbe', LEN('dcfgbe')), (13, 'dfcba', LEN('dfcba')), (13, 'gcaf', LEN('gcaf')), (13, 'degcfab', LEN('degcfab')), (13, 'afgcdb', LEN('afgcdb')),
 (14, 'cfagdb', LEN('cfagdb')), (14, 'gfbd', LEN('gfbd')), (14, 'fg', LEN('fg')), (14, 'badgfce', LEN('badgfce')), (14, 'gfc', LEN('gfc')), (14, 'ecdbfa', LEN('ecdbfa')), (14, 'bdfac', LEN('bdfac')), (14, 'gdafc', LEN('gdafc')), (14, 'fgeacb', LEN('fgeacb')), (14, 'edacg', LEN('edacg')),
 (15, 'fae', LEN('fae')), (15, 'ebgad', LEN('ebgad')), (15, 'cgfba', LEN('cgfba')), (15, 'bdfagc', LEN('bdfagc')), (15, 'fe', LEN('fe')), (15, 'ebfgdca', LEN('ebfgdca')), (15, 'bacdfe', LEN('bacdfe')), (15, 'cabegf', LEN('cabegf')), (15, 'egbaf', LEN('egbaf')), (15, 'egfc', LEN('egfc')),
 (16, 'gebfd', LEN('gebfd')), (16, 'aecf', LEN('aecf')), (16, 'ecgab', LEN('ecgab')), (16, 'cbagfd', LEN('cbagfd')), (16, 'cf', LEN('cf')), (16, 'gfecba', LEN('gfecba')), (16, 'dcbgafe', LEN('dcbgafe')), (16, 'cebfg', LEN('cebfg')), (16, 'dcbgea', LEN('dcbgea')), (16, 'cbf', LEN('cbf')),
 (17, 'agfed', LEN('agfed')), (17, 'fdaegcb', LEN('fdaegcb')), (17, 'facb', LEN('facb')), (17, 'ba', LEN('ba')), (17, 'bedfc', LEN('bedfc')), (17, 'abe', LEN('abe')), (17, 'edfba', LEN('edfba')), (17, 'begadc', LEN('begadc')), (17, 'gcdefb', LEN('gcdefb')), (17, 'dfcaeb', LEN('dfcaeb')),
 (18, 'dfb', LEN('dfb')), (18, 'fbdae', LEN('fbdae')), (18, 'eagcbf', LEN('eagcbf')), (18, 'baegd', LEN('baegd')), (18, 'fbcea', LEN('fbcea')), (18, 'cfde', LEN('cfde')), (18, 'aedcfb', LEN('aedcfb')), (18, 'df', LEN('df')), (18, 'gabdfc', LEN('gabdfc')), (18, 'fgadceb', LEN('fgadceb')),
 (19, 'acdbg', LEN('acdbg')), (19, 'ebaf', LEN('ebaf')), (19, 'fcadge', LEN('fcadge')), (19, 'bgf', LEN('bgf')), (19, 'dfgae', LEN('dfgae')), (19, 'gdafb', LEN('gdafb')), (19, 'fb', LEN('fb')), (19, 'gcfebda', LEN('gcfebda')), (19, 'fegdba', LEN('fegdba')), (19, 'gcfdbe', LEN('gcfdbe')),
 (20, 'ecadg', LEN('ecadg')), (20, 'gf', LEN('gf')), (20, 'dgabfc', LEN('dgabfc')), (20, 'fbedga', LEN('fbedga')), (20, 'bafdc', LEN('bafdc')), (20, 'bcgf', LEN('bcgf')), (20, 'gdf', LEN('gdf')), (20, 'gfcad', LEN('gfcad')), (20, 'dcagfeb', LEN('dcagfeb')), (20, 'aecfdb', LEN('aecfdb')),
 (21, 'cadbef', LEN('cadbef')), (21, 'dgef', LEN('dgef')), (21, 'eg', LEN('eg')), (21, 'fbeda', LEN('fbeda')), (21, 'gae', LEN('gae')), (21, 'efagbd', LEN('efagbd')), (21, 'cgdab', LEN('cgdab')), (21, 'bgfcae', LEN('bgfcae')), (21, 'adgeb', LEN('adgeb')), (21, 'cebdafg', LEN('cebdafg')),
 (22, 'edfgc', LEN('edfgc')), (22, 'ebdfc', LEN('ebdfc')), (22, 'cgfbda', LEN('cgfbda')), (22, 'gfbe', LEN('gfbe')), (22, 'cgbedf', LEN('cgbedf')), (22, 'bfd', LEN('bfd')), (22, 'fb', LEN('fb')), (22, 'edcba', LEN('edcba')), (22, 'gfedac', LEN('gfedac')), (22, 'dfgcaeb', LEN('dfgcaeb')),
 (23, 'gdbafce', LEN('gdbafce')), (23, 'fcedb', LEN('fcedb')), (23, 'cdea', LEN('cdea')), (23, 'cgebfa', LEN('cgebfa')), (23, 'gfbdac', LEN('gfbdac')), (23, 'dcb', LEN('dcb')), (23, 'afceb', LEN('afceb')), (23, 'dc', LEN('dc')), (23, 'bfedg', LEN('bfedg')), (23, 'fdbace', LEN('fdbace')),
 (24, 'dgbcae', LEN('dgbcae')), (24, 'eb', LEN('eb')), (24, 'begfa', LEN('begfa')), (24, 'egb', LEN('egb')), (24, 'gbadf', LEN('gbadf')), (24, 'cbgdafe', LEN('cbgdafe')), (24, 'efbacg', LEN('efbacg')), (24, 'ecgfa', LEN('ecgfa')), (24, 'cbfe', LEN('cbfe')), (24, 'dfgace', LEN('dfgace')),
 (25, 'dafbe', LEN('dafbe')), (25, 'ecfadgb', LEN('ecfadgb')), (25, 'dgb', LEN('dgb')), (25, 'gcdf', LEN('gcdf')), (25, 'ecbgfa', LEN('ecbgfa')), (25, 'dg', LEN('dg')), (25, 'fbgda', LEN('fbgda')), (25, 'adgbfc', LEN('adgbfc')), (25, 'ecbdga', LEN('ecbdga')), (25, 'gfacb', LEN('gfacb')),
 (26, 'df', LEN('df')), (26, 'fdc', LEN('fdc')), (26, 'bdecf', LEN('bdecf')), (26, 'gacfeb', LEN('gacfeb')), (26, 'cefgb', LEN('cefgb')), (26, 'bdaecfg', LEN('bdaecfg')), (26, 'gefd', LEN('gefd')), (26, 'fdbgca', LEN('fdbgca')), (26, 'edcab', LEN('edcab')), (26, 'bdefcg', LEN('bdefcg')),
 (27, 'egcdfab', LEN('egcdfab')), (27, 'aebfgd', LEN('aebfgd')), (27, 'abdce', LEN('abdce')), (27, 'bcgfad', LEN('bcgfad')), (27, 'fgdceb', LEN('fgdceb')), (27, 'gab', LEN('gab')), (27, 'gaebd', LEN('gaebd')), (27, 'ag', LEN('ag')), (27, 'bgedf', LEN('bgedf')), (27, 'feag', LEN('feag')),
 (28, 'acfebd', LEN('acfebd')), (28, 'febac', LEN('febac')), (28, 'deagfb', LEN('deagfb')), (28, 'bedfagc', LEN('bedfagc')), (28, 'efc', LEN('efc')), (28, 'afdbe', LEN('afdbe')), (28, 'eadc', LEN('eadc')), (28, 'ec', LEN('ec')), (28, 'bcagf', LEN('bcagf')), (28, 'gbefdc', LEN('gbefdc')),
 (29, 'cefga', LEN('cefga')), (29, 'fcaged', LEN('fcaged')), (29, 'dgef', LEN('dgef')), (29, 'gf', LEN('gf')), (29, 'fgabced', LEN('fgabced')), (29, 'bceag', LEN('bceag')), (29, 'cdfeab', LEN('cdfeab')), (29, 'fcabgd', LEN('fcabgd')), (29, 'dcafe', LEN('dcafe')), (29, 'gfa', LEN('gfa')),
 (30, 'gd', LEN('gd')), (30, 'bdeacf', LEN('bdeacf')), (30, 'fdbg', LEN('fdbg')), (30, 'egd', LEN('egd')), (30, 'fdecg', LEN('fdecg')), (30, 'gaecf', LEN('gaecf')), (30, 'dfebc', LEN('dfebc')), (30, 'gdabce', LEN('gdabce')), (30, 'dgecbf', LEN('dgecbf')), (30, 'cgedbaf', LEN('cgedbaf')),
 (31, 'ebcag', LEN('ebcag')), (31, 'agde', LEN('agde')), (31, 'baedcg', LEN('baedcg')), (31, 'dfacbe', LEN('dfacbe')), (31, 'bdacg', LEN('bdacg')), (31, 'da', LEN('da')), (31, 'gebadcf', LEN('gebadcf')), (31, 'dgfcb', LEN('dgfcb')), (31, 'agfbce', LEN('agfbce')), (31, 'dba', LEN('dba')),
 (32, 'deabc', LEN('deabc')), (32, 'acb', LEN('acb')), (32, 'facgbe', LEN('facgbe')), (32, 'bdecf', LEN('bdecf')), (32, 'abdgce', LEN('abdgce')), (32, 'feacgd', LEN('feacgd')), (32, 'cegdbaf', LEN('cegdbaf')), (32, 'ba', LEN('ba')), (32, 'cgade', LEN('cgade')), (32, 'bgda', LEN('bgda')),
 (33, 'cbgadef', LEN('cbgadef')), (33, 'fb', LEN('fb')), (33, 'abcdgf', LEN('abcdgf')), (33, 'bfac', LEN('bfac')), (33, 'gefda', LEN('gefda')), (33, 'gdabf', LEN('gdabf')), (33, 'dfb', LEN('dfb')), (33, 'acbdg', LEN('acbdg')), (33, 'cdegfb', LEN('cdegfb')), (33, 'agcebd', LEN('agcebd')),
 (34, 'ecbdfga', LEN('ecbdfga')), (34, 'cagbef', LEN('cagbef')), (34, 'afged', LEN('afged')), (34, 'efdgc', LEN('efdgc')), (34, 'cagdbe', LEN('cagdbe')), (34, 'efabdg', LEN('efabdg')), (34, 'gda', LEN('gda')), (34, 'da', LEN('da')), (34, 'geafb', LEN('geafb')), (34, 'fabd', LEN('fabd')),
 (35, 'fabgde', LEN('fabgde')), (35, 'bfec', LEN('bfec')), (35, 'bcafg', LEN('bcafg')), (35, 'bc', LEN('bc')), (35, 'fcgad', LEN('fcgad')), (35, 'gcebda', LEN('gcebda')), (35, 'cabegf', LEN('cabegf')), (35, 'cab', LEN('cab')), (35, 'eabfg', LEN('eabfg')), (35, 'eadcgfb', LEN('eadcgfb')),
 (36, 'dgb', LEN('dgb')), (36, 'fgbca', LEN('fgbca')), (36, 'gdbca', LEN('gdbca')), (36, 'ceagdb', LEN('ceagdb')), (36, 'dcgea', LEN('dcgea')), (36, 'gcfdea', LEN('gcfdea')), (36, 'db', LEN('db')), (36, 'dbeafcg', LEN('dbeafcg')), (36, 'cebd', LEN('cebd')), (36, 'fbaedg', LEN('fbaedg')),
 (37, 'bgcedaf', LEN('bgcedaf')), (37, 'dfgbae', LEN('dfgbae')), (37, 'efbag', LEN('efbag')), (37, 'gabcdf', LEN('gabcdf')), (37, 'bfacde', LEN('bfacde')), (37, 'gb', LEN('gb')), (37, 'gfeca', LEN('gfeca')), (37, 'bedg', LEN('bedg')), (37, 'bafde', LEN('bafde')), (37, 'gab', LEN('gab')),
 (38, 'becga', LEN('becga')), (38, 'fcgabd', LEN('fcgabd')), (38, 'efabc', LEN('efabc')), (38, 'cadfeg', LEN('cadfeg')), (38, 'bf', LEN('bf')), (38, 'daefc', LEN('daefc')), (38, 'dbef', LEN('dbef')), (38, 'fbcaed', LEN('fbcaed')), (38, 'afb', LEN('afb')), (38, 'gbacfde', LEN('gbacfde')),
 (39, 'dgcf', LEN('dgcf')), (39, 'egfbda', LEN('egfbda')), (39, 'dgfecb', LEN('dgfecb')), (39, 'becfga', LEN('becfga')), (39, 'dbefg', LEN('dbefg')), (39, 'dabec', LEN('dabec')), (39, 'cfe', LEN('cfe')), (39, 'ebcfd', LEN('ebcfd')), (39, 'cf', LEN('cf')), (39, 'dbgaecf', LEN('dbgaecf')),
 (40, 'gb', LEN('gb')), (40, 'fbegad', LEN('fbegad')), (40, 'bfag', LEN('bfag')), (40, 'gdefc', LEN('gdefc')), (40, 'cedbfa', LEN('cedbfa')), (40, 'cbaged', LEN('cbaged')), (40, 'afedb', LEN('afedb')), (40, 'dbg', LEN('dbg')), (40, 'dgeafbc', LEN('dgeafbc')), (40, 'gdfbe', LEN('gdfbe')),
 (41, 'cgbfae', LEN('cgbfae')), (41, 'fdbgca', LEN('fdbgca')), (41, 'dbcfe', LEN('dbcfe')), (41, 'bedgaf', LEN('bedgaf')), (41, 'daf', LEN('daf')), (41, 'fabge', LEN('fabge')), (41, 'ad', LEN('ad')), (41, 'gead', LEN('gead')), (41, 'beadf', LEN('beadf')), (41, 'geacbdf', LEN('geacbdf')),
 (42, 'bcfged', LEN('bcfged')), (42, 'fagce', LEN('fagce')), (42, 'gfbadec', LEN('gfbadec')), (42, 'abdceg', LEN('abdceg')), (42, 'ad', LEN('ad')), (42, 'cafed', LEN('cafed')), (42, 'bfedca', LEN('bfedca')), (42, 'bcdfe', LEN('bcdfe')), (42, 'dafb', LEN('dafb')), (42, 'acd', LEN('acd')),
 (43, 'bdafc', LEN('bdafc')), (43, 'fed', LEN('fed')), (43, 'cfega', LEN('cfega')), (43, 'dcbfae', LEN('dcbfae')), (43, 'agfcdb', LEN('agfcdb')), (43, 'caedf', LEN('caedf')), (43, 'egbcfd', LEN('egbcfd')), (43, 'dbea', LEN('dbea')), (43, 'gaedcbf', LEN('gaedcbf')), (43, 'de', LEN('de')),
 (44, 'afdec', LEN('afdec')), (44, 'bc', LEN('bc')), (44, 'gebaf', LEN('gebaf')), (44, 'egbdac', LEN('egbdac')), (44, 'fgbc', LEN('fgbc')), (44, 'afcbeg', LEN('afcbeg')), (44, 'gcbaefd', LEN('gcbaefd')), (44, 'bce', LEN('bce')), (44, 'abegdf', LEN('abegdf')), (44, 'ebfac', LEN('ebfac')),
 (45, 'debga', LEN('debga')), (45, 'gaecdbf', LEN('gaecdbf')), (45, 'fgebca', LEN('fgebca')), (45, 'aeg', LEN('aeg')), (45, 'ae', LEN('ae')), (45, 'ebadfg', LEN('ebadfg')), (45, 'dgbce', LEN('dgbce')), (45, 'dgfabc', LEN('dgfabc')), (45, 'dbafg', LEN('dbafg')), (45, 'efad', LEN('efad')),
 (46, 'fegbac', LEN('fegbac')), (46, 'bgaed', LEN('bgaed')), (46, 'gacd', LEN('gacd')), (46, 'cegadbf', LEN('cegadbf')), (46, 'dg', LEN('dg')), (46, 'acbge', LEN('acbge')), (46, 'dge', LEN('dge')), (46, 'fdbea', LEN('fdbea')), (46, 'dgbfec', LEN('dgbfec')), (46, 'cbdage', LEN('cbdage')),
 (47, 'gdcfe', LEN('gdcfe')), (47, 'debgcf', LEN('debgcf')), (47, 'bc', LEN('bc')), (47, 'gcb', LEN('gcb')), (47, 'dfcgb', LEN('dfcgb')), (47, 'gbafd', LEN('gbafd')), (47, 'eacgfd', LEN('eacgfd')), (47, 'acebdfg', LEN('acebdfg')), (47, 'edcb', LEN('edcb')), (47, 'begafc', LEN('begafc')),
 (48, 'gfbc', LEN('gfbc')), (48, 'gb', LEN('gb')), (48, 'gcabd', LEN('gcabd')), (48, 'eagfcd', LEN('eagfcd')), (48, 'dfgca', LEN('dfgca')), (48, 'fcdbag', LEN('fcdbag')), (48, 'eadbc', LEN('eadbc')), (48, 'gba', LEN('gba')), (48, 'fdgeba', LEN('fdgeba')), (48, 'dgbface', LEN('dgbface')),
 (49, 'edabfc', LEN('edabfc')), (49, 'cagbf', LEN('cagbf')), (49, 'cb', LEN('cb')), (49, 'acgfbe', LEN('acgfbe')), (49, 'bfc', LEN('bfc')), (49, 'facgde', LEN('facgde')), (49, 'agdfb', LEN('agdfb')), (49, 'bceg', LEN('bceg')), (49, 'bacdgfe', LEN('bacdgfe')), (49, 'fegca', LEN('fegca'))
  INSERT INTO @input VALUES
 (50, 'aecbd', LEN('aecbd')), (50, 'gecba', LEN('gecba')), (50, 'fecdab', LEN('fecdab')), (50, 'acfd', LEN('acfd')), (50, 'fgbade', LEN('fgbade')), (50, 'ebcdf', LEN('ebcdf')), (50, 'da', LEN('da')), (50, 'egcdabf', LEN('egcdabf')), (50, 'fdbgec', LEN('fdbgec')), (50, 'abd', LEN('abd')),
 (51, 'egbdc', LEN('egbdc')), (51, 'dfaceg', LEN('dfaceg')), (51, 'dfbcg', LEN('dfbcg')), (51, 'gbeacd', LEN('gbeacd')), (51, 'fgc', LEN('fgc')), (51, 'gbcfaed', LEN('gbcfaed')), (51, 'fdgba', LEN('fdgba')), (51, 'gbecfd', LEN('gbecfd')), (51, 'bcfe', LEN('bcfe')), (51, 'fc', LEN('fc')),
 (52, 'decgfba', LEN('decgfba')), (52, 'adfe', LEN('adfe')), (52, 'agf', LEN('agf')), (52, 'fgadbc', LEN('fgadbc')), (52, 'gcdefa', LEN('gcdefa')), (52, 'eacgf', LEN('eacgf')), (52, 'gceda', LEN('gceda')), (52, 'fbgce', LEN('fbgce')), (52, 'fa', LEN('fa')), (52, 'cbdega', LEN('cbdega')),
 (53, 'acfe', LEN('acfe')), (53, 'feagb', LEN('feagb')), (53, 'cfgebd', LEN('cfgebd')), (53, 'gbcda', LEN('gbcda')), (53, 'fcgab', LEN('fcgab')), (53, 'fgc', LEN('fgc')), (53, 'gbefda', LEN('gbefda')), (53, 'agfbec', LEN('agfbec')), (53, 'cf', LEN('cf')), (53, 'gbacfde', LEN('gbacfde')),
 (54, 'gfdc', LEN('gfdc')), (54, 'acgbfd', LEN('acgbfd')), (54, 'dgafb', LEN('dgafb')), (54, 'fcadeb', LEN('fcadeb')), (54, 'fbc', LEN('fbc')), (54, 'eagbc', LEN('eagbc')), (54, 'adegfb', LEN('adegfb')), (54, 'adgcefb', LEN('adgcefb')), (54, 'fc', LEN('fc')), (54, 'acgbf', LEN('acgbf')),
 (55, 'gfcbad', LEN('gfcbad')), (55, 'dbgcae', LEN('dbgcae')), (55, 'cegafdb', LEN('cegafdb')), (55, 'fegbda', LEN('fegbda')), (55, 'efdab', LEN('efdab')), (55, 'geadb', LEN('geadb')), (55, 'befcd', LEN('befcd')), (55, 'af', LEN('af')), (55, 'abf', LEN('abf')), (55, 'faeg', LEN('faeg')),
 (56, 'fed', LEN('fed')), (56, 'defgc', LEN('defgc')), (56, 'acgfbed', LEN('acgfbed')), (56, 'dbegfc', LEN('dbegfc')), (56, 'fegdba', LEN('fegdba')), (56, 'ed', LEN('ed')), (56, 'efgca', LEN('efgca')), (56, 'bfdgc', LEN('bfdgc')), (56, 'cagdfb', LEN('cagdfb')), (56, 'ebdc', LEN('ebdc')),
 (57, 'gfdeb', LEN('gfdeb')), (57, 'fcegab', LEN('fcegab')), (57, 'bgdcea', LEN('bgdcea')), (57, 'dbe', LEN('dbe')), (57, 'acfgbde', LEN('acfgbde')), (57, 'dbefag', LEN('dbefag')), (57, 'daef', LEN('daef')), (57, 'de', LEN('de')), (57, 'aegbf', LEN('aegbf')), (57, 'dgbfc', LEN('dgbfc')),
 (58, 'fbead', LEN('fbead')), (58, 'ega', LEN('ega')), (58, 'fegacd', LEN('fegacd')), (58, 'ag', LEN('ag')), (58, 'degba', LEN('degba')), (58, 'egdbc', LEN('egdbc')), (58, 'gbcfaed', LEN('gbcfaed')), (58, 'abecfd', LEN('abecfd')), (58, 'gedbfa', LEN('gedbfa')), (58, 'fbag', LEN('fbag')),
 (59, 'cgbdef', LEN('cgbdef')), (59, 'bcgafd', LEN('bcgafd')), (59, 'cgafb', LEN('cgafb')), (59, 'acgfd', LEN('acgfd')), (59, 'cfd', LEN('cfd')), (59, 'dc', LEN('dc')), (59, 'edgfa', LEN('edgfa')), (59, 'fbecgad', LEN('fbecgad')), (59, 'gfcaeb', LEN('gfcaeb')), (59, 'dacb', LEN('dacb')),
 (60, 'aebgc', LEN('aebgc')), (60, 'gefacdb', LEN('gefacdb')), (60, 'ac', LEN('ac')), (60, 'gbcfea', LEN('gbcfea')), (60, 'ace', LEN('ace')), (60, 'acfg', LEN('acfg')), (60, 'bafge', LEN('bafge')), (60, 'cabdfe', LEN('cabdfe')), (60, 'geabfd', LEN('geabfd')), (60, 'cgdeb', LEN('cgdeb')),
 (61, 'cbfage', LEN('cbfage')), (61, 'fbaed', LEN('fbaed')), (61, 'aebfdg', LEN('aebfdg')), (61, 'dfa', LEN('dfa')), (61, 'dbcfe', LEN('dbcfe')), (61, 'gabef', LEN('gabef')), (61, 'ecafdgb', LEN('ecafdgb')), (61, 'cdfega', LEN('cdfega')), (61, 'da', LEN('da')), (61, 'bdag', LEN('bdag')),
 (62, 'faegb', LEN('faegb')), (62, 'efcdba', LEN('efcdba')), (62, 'fdgce', LEN('fdgce')), (62, 'ecfdgb', LEN('ecfdgb')), (62, 'fca', LEN('fca')), (62, 'fgdaec', LEN('fgdaec')), (62, 'ca', LEN('ca')), (62, 'adgc', LEN('adgc')), (62, 'cfega', LEN('cfega')), (62, 'degabfc', LEN('degabfc')),
 (63, 'cgdbe', LEN('cgdbe')), (63, 'ecabgd', LEN('ecabgd')), (63, 'dagcb', LEN('dagcb')), (63, 'ac', LEN('ac')), (63, 'fgaecd', LEN('fgaecd')), (63, 'gfecbd', LEN('gfecbd')), (63, 'gfbda', LEN('gfbda')), (63, 'bfgedac', LEN('bfgedac')), (63, 'acg', LEN('acg')), (63, 'beca', LEN('beca')),
 (64, 'bce', LEN('bce')), (64, 'gcdae', LEN('gcdae')), (64, 'dabefc', LEN('dabefc')), (64, 'gabfcd', LEN('gabfcd')), (64, 'dacbe', LEN('dacbe')), (64, 'gefcdb', LEN('gefcdb')), (64, 'bcdfa', LEN('bcdfa')), (64, 'cadfegb', LEN('cadfegb')), (64, 'be', LEN('be')), (64, 'beaf', LEN('beaf')),
 (65, 'dfcgab', LEN('dfcgab')), (65, 'eadgfb', LEN('eadgfb')), (65, 'cg', LEN('cg')), (65, 'bgced', LEN('bgced')), (65, 'gdcabfe', LEN('gdcabfe')), (65, 'gfdeb', LEN('gfdeb')), (65, 'dbeca', LEN('dbeca')), (65, 'cbg', LEN('cbg')), (65, 'fgcedb', LEN('fgcedb')), (65, 'efgc', LEN('efgc')),
 (66, 'ae', LEN('ae')), (66, 'fbgeca', LEN('fbgeca')), (66, 'dabcf', LEN('dabcf')), (66, 'cae', LEN('cae')), (66, 'dgbeac', LEN('dgbeac')), (66, 'fadecbg', LEN('fadecbg')), (66, 'egbcd', LEN('egbcd')), (66, 'eagd', LEN('eagd')), (66, 'bgfced', LEN('bgfced')), (66, 'bdace', LEN('bdace')),
 (67, 'dgbfca', LEN('dgbfca')), (67, 'afdge', LEN('afdge')), (67, 'fag', LEN('fag')), (67, 'cgedf', LEN('cgedf')), (67, 'abdef', LEN('abdef')), (67, 'gbea', LEN('gbea')), (67, 'bfaedg', LEN('bfaedg')), (67, 'abefcd', LEN('abefcd')), (67, 'ag', LEN('ag')), (67, 'bgcaefd', LEN('bgcaefd')),
 (68, 'eagf', LEN('eagf')), (68, 'bcgfde', LEN('bcgfde')), (68, 'gadeb', LEN('gadeb')), (68, 'ge', LEN('ge')), (68, 'bfecadg', LEN('bfecadg')), (68, 'cadfbe', LEN('cadfbe')), (68, 'gcdba', LEN('gcdba')), (68, 'efbda', LEN('efbda')), (68, 'deagfb', LEN('deagfb')), (68, 'deg', LEN('deg')),
 (69, 'dcegbaf', LEN('dcegbaf')), (69, 'aebdgf', LEN('aebdgf')), (69, 'cagfe', LEN('cagfe')), (69, 'acgedb', LEN('acgedb')), (69, 'agdeb', LEN('agdeb')), (69, 'ecbd', LEN('ecbd')), (69, 'cfbdag', LEN('cfbdag')), (69, 'adc', LEN('adc')), (69, 'gdeac', LEN('gdeac')), (69, 'cd', LEN('cd')),
 (70, 'bcgeaf', LEN('bcgeaf')), (70, 'dacbg', LEN('dacbg')), (70, 'agcbdf', LEN('agcbdf')), (70, 'bacged', LEN('bacged')), (70, 'afgd', LEN('afgd')), (70, 'cdafb', LEN('cdafb')), (70, 'af', LEN('af')), (70, 'egadcbf', LEN('egadcbf')), (70, 'caf', LEN('caf')), (70, 'fcebd', LEN('fcebd')),
 (71, 'bgdac', LEN('bgdac')), (71, 'bagfcd', LEN('bagfcd')), (71, 'ebg', LEN('ebg')), (71, 'cedg', LEN('cedg')), (71, 'eg', LEN('eg')), (71, 'ecafb', LEN('ecafb')), (71, 'dgeafb', LEN('dgeafb')), (71, 'egabc', LEN('egabc')), (71, 'dbagce', LEN('dbagce')), (71, 'adbecfg', LEN('adbecfg')),
 (72, 'ab', LEN('ab')), (72, 'ebfgd', LEN('ebfgd')), (72, 'bfa', LEN('bfa')), (72, 'efbcag', LEN('efbcag')), (72, 'cgafedb', LEN('cgafedb')), (72, 'abdc', LEN('abdc')), (72, 'eafdc', LEN('eafdc')), (72, 'bdaef', LEN('bdaef')), (72, 'acfbed', LEN('acfbed')), (72, 'cegafd', LEN('cegafd')),
 (73, 'badcf', LEN('badcf')), (73, 'bdgcf', LEN('bdgcf')), (73, 'fbgcde', LEN('fbgcde')), (73, 'cagb', LEN('cagb')), (73, 'bgfdca', LEN('bgfdca')), (73, 'ca', LEN('ca')), (73, 'fcgead', LEN('fcgead')), (73, 'dafeb', LEN('dafeb')), (73, 'gfcbead', LEN('gfcbead')), (73, 'cad', LEN('cad')),
 (74, 'ebfgad', LEN('ebfgad')), (74, 'bcgedaf', LEN('bcgedaf')), (74, 'egfcb', LEN('egfcb')), (74, 'aebfg', LEN('aebfg')), (74, 'acgfde', LEN('acgfde')), (74, 'geadf', LEN('geadf')), (74, 'bfa', LEN('bfa')), (74, 'ba', LEN('ba')), (74, 'fadcgb', LEN('fadcgb')), (74, 'edba', LEN('edba')),
 (75, 'cfedagb', LEN('cfedagb')), (75, 'fbecg', LEN('fbecg')), (75, 'cdegfb', LEN('cdegfb')), (75, 'gbcafd', LEN('gbcafd')), (75, 'edgb', LEN('edgb')), (75, 'bd', LEN('bd')), (75, 'gaecbf', LEN('gaecbf')), (75, 'fdebc', LEN('fdebc')), (75, 'adecf', LEN('adecf')), (75, 'fbd', LEN('fbd')),
 (76, 'gcdaef', LEN('gcdaef')), (76, 'bedcga', LEN('bedcga')), (76, 'fagd', LEN('fagd')), (76, 'gceda', LEN('gceda')), (76, 'fa', LEN('fa')), (76, 'abcfeg', LEN('abcfeg')), (76, 'efa', LEN('efa')), (76, 'eacfd', LEN('eacfd')), (76, 'efgbdac', LEN('efgbdac')), (76, 'fdebc', LEN('fdebc')),
 (77, 'ae', LEN('ae')), (77, 'eda', LEN('eda')), (77, 'efdcagb', LEN('efdcagb')), (77, 'decgf', LEN('decgf')), (77, 'gacbd', LEN('gacbd')), (77, 'fecadb', LEN('fecadb')), (77, 'gacde', LEN('gacde')), (77, 'acdgfb', LEN('acdgfb')), (77, 'ebag', LEN('ebag')), (77, 'cdageb', LEN('cdageb')),
 (78, 'acbef', LEN('acbef')), (78, 'ga', LEN('ga')), (78, 'dgcbe', LEN('dgcbe')), (78, 'bgfa', LEN('bgfa')), (78, 'gcefab', LEN('gcefab')), (78, 'bagce', LEN('bagce')), (78, 'dfacbe', LEN('dfacbe')), (78, 'agcedf', LEN('agcedf')), (78, 'cga', LEN('cga')), (78, 'gadfbce', LEN('gadfbce')),
 (79, 'afebdcg', LEN('afebdcg')), (79, 'bedacg', LEN('bedacg')), (79, 'dgf', LEN('dgf')), (79, 'abgfc', LEN('abgfc')), (79, 'df', LEN('df')), (79, 'fgdbce', LEN('fgdbce')), (79, 'agfbd', LEN('agfbd')), (79, 'fbeadg', LEN('fbeadg')), (79, 'dafe', LEN('dafe')), (79, 'egabd', LEN('egabd')),
 (80, 'eb', LEN('eb')), (80, 'dacebg', LEN('dacebg')), (80, 'cfadb', LEN('cfadb')), (80, 'cdfaeg', LEN('cdfaeg')), (80, 'adgec', LEN('adgec')), (80, 'efagdb', LEN('efagdb')), (80, 'bcgedaf', LEN('bcgedaf')), (80, 'edb', LEN('edb')), (80, 'cdbea', LEN('cdbea')), (80, 'gcbe', LEN('gcbe')),
 (81, 'cegdf', LEN('cegdf')), (81, 'feagbd', LEN('feagbd')), (81, 'badegfc', LEN('badegfc')), (81, 'fedag', LEN('fedag')), (81, 'adfb', LEN('adfb')), (81, 'abegdc', LEN('abegdc')), (81, 'gad', LEN('gad')), (81, 'agebf', LEN('agebf')), (81, 'ad', LEN('ad')), (81, 'bgcefa', LEN('bgcefa')),
 (82, 'fec', LEN('fec')), (82, 'eadfg', LEN('eadfg')), (82, 'aefcd', LEN('aefcd')), (82, 'fecgdab', LEN('fecgdab')), (82, 'efacgd', LEN('efacgd')), (82, 'bafdc', LEN('bafdc')), (82, 'bgdfce', LEN('bgdfce')), (82, 'eagc', LEN('eagc')), (82, 'dbagfe', LEN('dbagfe')), (82, 'ec', LEN('ec')),
 (83, 'beacdf', LEN('beacdf')), (83, 'dc', LEN('dc')), (83, 'dec', LEN('dec')), (83, 'abced', LEN('abced')), (83, 'aebgcf', LEN('aebgcf')), (83, 'afcbe', LEN('afcbe')), (83, 'cdfb', LEN('cdfb')), (83, 'adgbe', LEN('adgbe')), (83, 'cdfgae', LEN('cdfgae')), (83, 'decgabf', LEN('decgabf')),
 (84, 'ebgacf', LEN('ebgacf')), (84, 'cfde', LEN('cfde')), (84, 'abegcd', LEN('abegcd')), (84, 'abfec', LEN('abfec')), (84, 'eadcfb', LEN('eadcfb')), (84, 'ed', LEN('ed')), (84, 'dae', LEN('dae')), (84, 'fabgcde', LEN('fabgcde')), (84, 'bdfag', LEN('bdfag')), (84, 'baefd', LEN('baefd')),
 (85, 'dc', LEN('dc')), (85, 'gaedb', LEN('gaedb')), (85, 'dfgc', LEN('dfgc')), (85, 'dbc', LEN('dbc')), (85, 'abgcef', LEN('abgcef')), (85, 'gebdc', LEN('gebdc')), (85, 'cbgef', LEN('cbgef')), (85, 'bedcaf', LEN('bedcaf')), (85, 'bcadgef', LEN('bcadgef')), (85, 'dbfcge', LEN('dbfcge')),
 (86, 'fbdagc', LEN('fbdagc')), (86, 'degba', LEN('degba')), (86, 'dgbaec', LEN('dgbaec')), (86, 'cfedabg', LEN('cfedabg')), (86, 'gd', LEN('gd')), (86, 'beagc', LEN('beagc')), (86, 'deabf', LEN('deabf')), (86, 'agd', LEN('agd')), (86, 'cfagbe', LEN('cfagbe')), (86, 'cedg', LEN('cedg')),
 (87, 'gdafc', LEN('gdafc')), (87, 'dcfgba', LEN('dcfgba')), (87, 'gbd', LEN('gbd')), (87, 'dbefcg', LEN('dbefcg')), (87, 'agebc', LEN('agebc')), (87, 'dafb', LEN('dafb')), (87, 'bgcda', LEN('bgcda')), (87, 'bd', LEN('bd')), (87, 'fgecad', LEN('fgecad')), (87, 'cdagefb', LEN('cdagefb')),
 (88, 'bgaec', LEN('bgaec')), (88, 'fcedb', LEN('fcedb')), (88, 'cgabde', LEN('cgabde')), (88, 'efgcab', LEN('efgcab')), (88, 'efgcb', LEN('efgcb')), (88, 'fg', LEN('fg')), (88, 'edgbfa', LEN('edgbfa')), (88, 'fge', LEN('fge')), (88, 'gaefcbd', LEN('gaefcbd')), (88, 'cagf', LEN('cagf')),
 (89, 'bga', LEN('bga')), (89, 'cabged', LEN('cabged')), (89, 'eagdfc', LEN('eagdfc')), (89, 'acfgdeb', LEN('acfgdeb')), (89, 'ab', LEN('ab')), (89, 'bcgad', LEN('bcgad')), (89, 'dgcae', LEN('dgcae')), (89, 'bcea', LEN('bcea')), (89, 'bdefga', LEN('bdefga')), (89, 'dcfgb', LEN('dcfgb')),
 (90, 'adfbeg', LEN('adfbeg')), (90, 'egb', LEN('egb')), (90, 'gcfba', LEN('gcfba')), (90, 'eg', LEN('eg')), (90, 'cbfagd', LEN('cbfagd')), (90, 'cgef', LEN('cgef')), (90, 'bagec', LEN('bagec')), (90, 'cbead', LEN('cbead')), (90, 'cbfgead', LEN('cbfgead')), (90, 'bfcgae', LEN('bfcgae')),
 (91, 'cegbadf', LEN('cegbadf')), (91, 'cagef', LEN('cagef')), (91, 'bdagcf', LEN('bdagcf')), (91, 'acdeb', LEN('acdeb')), (91, 'abg', LEN('abg')), (91, 'bdgeac', LEN('bdgeac')), (91, 'bfcade', LEN('bfcade')), (91, 'gedb', LEN('gedb')), (91, 'begac', LEN('begac')), (91, 'bg', LEN('bg')),
 (92, 'fgecb', LEN('fgecb')), (92, 'dbgafc', LEN('dbgafc')), (92, 'cgb', LEN('cgb')), (92, 'debg', LEN('debg')), (92, 'bfgced', LEN('bfgced')), (92, 'cebfd', LEN('cebfd')), (92, 'faegc', LEN('faegc')), (92, 'abfdce', LEN('abfdce')), (92, 'bg', LEN('bg')), (92, 'bfedgca', LEN('bfedgca')),
 (93, 'fdgce', LEN('fdgce')), (93, 'gbecf', LEN('gbecf')), (93, 'cd', LEN('cd')), (93, 'cgabedf', LEN('cgabedf')), (93, 'gfdae', LEN('gfdae')), (93, 'cgbdfe', LEN('cgbdfe')), (93, 'gacebf', LEN('gacebf')), (93, 'ebdafc', LEN('ebdafc')), (93, 'fdc', LEN('fdc')), (93, 'bcdg', LEN('bcdg')),
 (94, 'ebcgdfa', LEN('ebcgdfa')), (94, 'cfdabg', LEN('cfdabg')), (94, 'befg', LEN('befg')), (94, 'efdac', LEN('efdac')), (94, 'eb', LEN('eb')), (94, 'gfabce', LEN('gfabce')), (94, 'ebfac', LEN('ebfac')), (94, 'ebc', LEN('ebc')), (94, 'cfabg', LEN('cfabg')), (94, 'ecgbda', LEN('ecgbda')),
 (95, 'fdgabce', LEN('fdgabce')), (95, 'eagc', LEN('eagc')), (95, 'abecf', LEN('abecf')), (95, 'cfa', LEN('cfa')), (95, 'dbfacg', LEN('dbfacg')), (95, 'ac', LEN('ac')), (95, 'fcedb', LEN('fcedb')), (95, 'febadg', LEN('febadg')), (95, 'bgeaf', LEN('bgeaf')), (95, 'aecfgb', LEN('aecfgb')),
 (96, 'adeb', LEN('adeb')), (96, 'edagf', LEN('edagf')), (96, 'fegab', LEN('fegab')), (96, 'eb', LEN('eb')), (96, 'bef', LEN('bef')), (96, 'dagcfe', LEN('dagcfe')), (96, 'afgbc', LEN('afgbc')), (96, 'cgebdf', LEN('cgebdf')), (96, 'fdegba', LEN('fdegba')), (96, 'cfeadgb', LEN('cfeadgb')),
 (97, 'ecfbg', LEN('ecfbg')), (97, 'gbad', LEN('gbad')), (97, 'bacdef', LEN('bacdef')), (97, 'bd', LEN('bd')), (97, 'begcd', LEN('begcd')), (97, 'dcaefg', LEN('dcaefg')), (97, 'daegcb', LEN('daegcb')), (97, 'dbc', LEN('dbc')), (97, 'dgbafec', LEN('dgbafec')), (97, 'aegdc', LEN('aegdc')),
 (98, 'efcdg', LEN('efcdg')), (98, 'deb', LEN('deb')), (98, 'fbdec', LEN('fbdec')), (98, 'dgebca', LEN('dgebca')), (98, 'afecb', LEN('afecb')), (98, 'db', LEN('db')), (98, 'edagbfc', LEN('edagbfc')), (98, 'abecgf', LEN('abecgf')), (98, 'badf', LEN('badf')), (98, 'cbefda', LEN('cbefda')),
 (99, 'edbaf', LEN('edbaf')), (99, 'gf', LEN('gf')), (99, 'egfa', LEN('egfa')), (99, 'efabgd', LEN('efabgd')), (99, 'fbg', LEN('fbg')), (99, 'bfdaec', LEN('bfdaec')), (99, 'egdfbac', LEN('egdfbac')), (99, 'dcgab', LEN('dcgab')), (99, 'dabfg', LEN('dabfg')), (99, 'cbdfge', LEN('cbdfge'))
 
  INSERT INTO @input VALUES
 (100, 'cfegd', LEN('cfegd')), (100, 'aef', LEN('aef')), (100, 'bacgf', LEN('bacgf')), (100, 'dfacegb', LEN('dfacegb')), (100, 'cbfeda', LEN('cbfeda')), (100, 'ea', LEN('ea')), (100, 'cdgfba', LEN('cdgfba')), (100, 'afgceb', LEN('afgceb')), (100, 'gabe', LEN('gabe')), (100, 'gcefa', LEN('gcefa')),
 (101, 'dacbf', LEN('dacbf')), (101, 'cbgfd', LEN('cbgfd')), (101, 'fbecad', LEN('fbecad')), (101, 'edab', LEN('edab')), (101, 'ab', LEN('ab')), (101, 'gdecaf', LEN('gdecaf')), (101, 'cba', LEN('cba')), (101, 'fegbca', LEN('fegbca')), (101, 'decfa', LEN('decfa')), (101, 'afgbedc', LEN('afgbedc')),
 (102, 'bcgdef', LEN('bcgdef')), (102, 'ecfbag', LEN('ecfbag')), (102, 'bc', LEN('bc')), (102, 'cfdae', LEN('cfdae')), (102, 'ecb', LEN('ecb')), (102, 'becaf', LEN('becaf')), (102, 'gbac', LEN('gbac')), (102, 'bdgeaf', LEN('bdgeaf')), (102, 'egbdacf', LEN('egbdacf')), (102, 'agbef', LEN('agbef')),
 (103, 'ebcfg', LEN('ebcfg')), (103, 'dabegc', LEN('dabegc')), (103, 'fbdca', LEN('fbdca')), (103, 'dafecb', LEN('dafecb')), (103, 'cgbafd', LEN('cgbafd')), (103, 'edaf', LEN('edaf')), (103, 'acbfe', LEN('acbfe')), (103, 'eab', LEN('eab')), (103, 'ae', LEN('ae')), (103, 'bdecfag', LEN('bdecfag')),
 (104, 'dgafce', LEN('dgafce')), (104, 'bcgef', LEN('bcgef')), (104, 'fc', LEN('fc')), (104, 'gdefab', LEN('gdefab')), (104, 'abfc', LEN('abfc')), (104, 'dgbecaf', LEN('dgbecaf')), (104, 'ecf', LEN('ecf')), (104, 'bfaeg', LEN('bfaeg')), (104, 'acgefb', LEN('acgefb')), (104, 'gcedb', LEN('gcedb')),
 (105, 'gcbdea', LEN('gcbdea')), (105, 'cdfge', LEN('cdfge')), (105, 'cafedbg', LEN('cafedbg')), (105, 'aefc', LEN('aefc')), (105, 'adgce', LEN('adgce')), (105, 'cf', LEN('cf')), (105, 'cgf', LEN('cgf')), (105, 'febdg', LEN('febdg')), (105, 'gadcfe', LEN('gadcfe')), (105, 'fdgbca', LEN('fdgbca')),
 (106, 'gebadf', LEN('gebadf')), (106, 'agf', LEN('agf')), (106, 'fgec', LEN('fgec')), (106, 'gceadf', LEN('gceadf')), (106, 'fg', LEN('fg')), (106, 'cgfda', LEN('cgfda')), (106, 'geadcbf', LEN('geadcbf')), (106, 'abdgce', LEN('abdgce')), (106, 'acbdf', LEN('acbdf')), (106, 'eacgd', LEN('eacgd')),
 (107, 'dacfb', LEN('dacfb')), (107, 'cb', LEN('cb')), (107, 'cba', LEN('cba')), (107, 'dcabef', LEN('dcabef')), (107, 'ecdbfag', LEN('ecdbfag')), (107, 'ecbd', LEN('ecbd')), (107, 'eacdf', LEN('eacdf')), (107, 'agebcf', LEN('agebcf')), (107, 'acdgef', LEN('acdgef')), (107, 'gfbda', LEN('gfbda')),
 (108, 'gecbaf', LEN('gecbaf')), (108, 'gdfec', LEN('gdfec')), (108, 'gefda', LEN('gefda')), (108, 'fbgcd', LEN('fbgcd')), (108, 'ec', LEN('ec')), (108, 'fgbcda', LEN('fgbcda')), (108, 'gfcbaed', LEN('gfcbaed')), (108, 'edfgcb', LEN('edfgcb')), (108, 'cge', LEN('cge')), (108, 'dbec', LEN('dbec')),
 (109, 'fcagde', LEN('fcagde')), (109, 'cagb', LEN('cagb')), (109, 'ca', LEN('ca')), (109, 'acgfbd', LEN('acgfbd')), (109, 'dbcfge', LEN('dbcfge')), (109, 'bdfcg', LEN('bdfcg')), (109, 'acf', LEN('acf')), (109, 'dfcba', LEN('dfcba')), (109, 'acebgfd', LEN('acebgfd')), (109, 'beafd', LEN('beafd')),
 (110, 'cdfga', LEN('cdfga')), (110, 'cdaegf', LEN('cdaegf')), (110, 'dacefbg', LEN('dacefbg')), (110, 'abcd', LEN('abcd')), (110, 'db', LEN('db')), (110, 'bgcfd', LEN('bgcfd')), (110, 'acbgdf', LEN('acbgdf')), (110, 'bagfde', LEN('bagfde')), (110, 'gbefc', LEN('gbefc')), (110, 'bdg', LEN('bdg')),
 (111, 'cbedf', LEN('cbedf')), (111, 'ecagb', LEN('ecagb')), (111, 'gfbacde', LEN('gfbacde')), (111, 'dbag', LEN('dbag')), (111, 'dgbce', LEN('dgbce')), (111, 'bfeagc', LEN('bfeagc')), (111, 'gacedb', LEN('gacedb')), (111, 'cgd', LEN('cgd')), (111, 'gdfcea', LEN('gdfcea')), (111, 'gd', LEN('gd')),
 (112, 'cdgfbae', LEN('cdgfbae')), (112, 'agcdef', LEN('agcdef')), (112, 'ecagd', LEN('ecagd')), (112, 'egdabf', LEN('egdabf')), (112, 'aeg', LEN('aeg')), (112, 'eg', LEN('eg')), (112, 'bdcga', LEN('bdcga')), (112, 'cfaedb', LEN('cfaedb')), (112, 'afcde', LEN('afcde')), (112, 'ecfg', LEN('ecfg')),
 (113, 'fgdba', LEN('fgdba')), (113, 'agecb', LEN('agecb')), (113, 'dacegf', LEN('dacegf')), (113, 'abedfg', LEN('abedfg')), (113, 'gadcbf', LEN('gadcbf')), (113, 'bdfaecg', LEN('bdfaecg')), (113, 'cf', LEN('cf')), (113, 'bfcd', LEN('bfcd')), (113, 'gfc', LEN('gfc')), (113, 'bfgac', LEN('bfgac')),
 (114, 'cgfba', LEN('cgfba')), (114, 'gfeab', LEN('gfeab')), (114, 'ceafbd', LEN('ceafbd')), (114, 'ae', LEN('ae')), (114, 'dbegf', LEN('dbegf')), (114, 'cgbfeda', LEN('cgbfeda')), (114, 'fgcbad', LEN('fgcbad')), (114, 'geca', LEN('geca')), (114, 'ecabfg', LEN('ecabfg')), (114, 'efa', LEN('efa')),
 (115, 'fecgda', LEN('fecgda')), (115, 'decgb', LEN('decgb')), (115, 'efg', LEN('efg')), (115, 'ebfcgad', LEN('ebfcgad')), (115, 'acbfdg', LEN('acbfdg')), (115, 'acfe', LEN('acfe')), (115, 'ef', LEN('ef')), (115, 'fcgda', LEN('fcgda')), (115, 'dbfgae', LEN('dbfgae')), (115, 'egfcd', LEN('egfcd')),
 (116, 'eca', LEN('eca')), (116, 'cadfg', LEN('cadfg')), (116, 'ecagfb', LEN('ecagfb')), (116, 'fcagdbe', LEN('fcagdbe')), (116, 'efbcdg', LEN('efbcdg')), (116, 'edgca', LEN('edgca')), (116, 'bdae', LEN('bdae')), (116, 'bgcde', LEN('bgcde')), (116, 'ea', LEN('ea')), (116, 'eadcbg', LEN('eadcbg')),
 (117, 'ecgfbd', LEN('ecgfbd')), (117, 'fce', LEN('fce')), (117, 'aedcf', LEN('aedcf')), (117, 'dcegab', LEN('dcegab')), (117, 'dcega', LEN('dcega')), (117, 'dgfcea', LEN('dgfcea')), (117, 'fe', LEN('fe')), (117, 'dfacb', LEN('dfacb')), (117, 'geaf', LEN('geaf')), (117, 'cfgaebd', LEN('cfgaebd')),
 (118, 'beafdcg', LEN('beafdcg')), (118, 'acbeg', LEN('acbeg')), (118, 'fcegda', LEN('fcegda')), (118, 'gcf', LEN('gcf')), (118, 'badfge', LEN('badfge')), (118, 'fc', LEN('fc')), (118, 'cfbadg', LEN('cfbadg')), (118, 'fgdae', LEN('fgdae')), (118, 'egcfa', LEN('egcfa')), (118, 'cedf', LEN('cedf')),
 (119, 'gdf', LEN('gdf')), (119, 'bdcef', LEN('bdcef')), (119, 'bfaeg', LEN('bfaeg')), (119, 'dceg', LEN('dceg')), (119, 'fdbgce', LEN('fdbgce')), (119, 'fdgcbea', LEN('fdgcbea')), (119, 'gfdabc', LEN('gfdabc')), (119, 'bgedf', LEN('bgedf')), (119, 'dg', LEN('dg')), (119, 'facdbe', LEN('facdbe')),
 (120, 'gac', LEN('gac')), (120, 'cfbged', LEN('cfbged')), (120, 'cgbae', LEN('cgbae')), (120, 'agedb', LEN('agedb')), (120, 'ac', LEN('ac')), (120, 'ecgbafd', LEN('ecgbafd')), (120, 'faec', LEN('faec')), (120, 'ecgbaf', LEN('ecgbaf')), (120, 'cgdfab', LEN('cgdfab')), (120, 'gcfeb', LEN('gcfeb')),
 (121, 'dbafge', LEN('dbafge')), (121, 'face', LEN('face')), (121, 'abgcf', LEN('abgcf')), (121, 'ecgadb', LEN('ecgadb')), (121, 'fbcgd', LEN('fbcgd')), (121, 'adcefbg', LEN('adcefbg')), (121, 'fgbae', LEN('fgbae')), (121, 'afbgce', LEN('afbgce')), (121, 'agc', LEN('agc')), (121, 'ac', LEN('ac')),
 (122, 'aefdb', LEN('aefdb')), (122, 'bfdgc', LEN('bfdgc')), (122, 'fgbadce', LEN('fgbadce')), (122, 'dcegbf', LEN('dcegbf')), (122, 'ag', LEN('ag')), (122, 'adg', LEN('adg')), (122, 'dgfabc', LEN('dgfabc')), (122, 'bgafd', LEN('bgafd')), (122, 'dabceg', LEN('dabceg')), (122, 'cfga', LEN('cfga')),
 (123, 'fdaeb', LEN('fdaeb')), (123, 'fecb', LEN('fecb')), (123, 'fecbda', LEN('fecbda')), (123, 'bfgcda', LEN('bfgcda')), (123, 'dfebag', LEN('dfebag')), (123, 'cab', LEN('cab')), (123, 'bcade', LEN('bcade')), (123, 'cb', LEN('cb')), (123, 'ecgda', LEN('ecgda')), (123, 'fdbagce', LEN('fdbagce')),
 (124, 'gf', LEN('gf')), (124, 'gcbfad', LEN('gcbfad')), (124, 'becdagf', LEN('becdagf')), (124, 'bfeg', LEN('bfeg')), (124, 'agcfe', LEN('agcfe')), (124, 'deafc', LEN('deafc')), (124, 'agdecb', LEN('agdecb')), (124, 'cbgaef', LEN('cbgaef')), (124, 'ceabg', LEN('ceabg')), (124, 'gcf', LEN('gcf')),
 (125, 'afgecd', LEN('afgecd')), (125, 'gdefb', LEN('gdefb')), (125, 'abfc', LEN('abfc')), (125, 'cefbga', LEN('cefbga')), (125, 'gaebf', LEN('gaebf')), (125, 'dbfagec', LEN('dbfagec')), (125, 'gab', LEN('gab')), (125, 'ab', LEN('ab')), (125, 'gacef', LEN('gacef')), (125, 'cgaedb', LEN('cgaedb')),
 (126, 'ebfac', LEN('ebfac')), (126, 'fcd', LEN('fcd')), (126, 'egabcf', LEN('egabcf')), (126, 'aecfdb', LEN('aecfdb')), (126, 'efcad', LEN('efcad')), (126, 'dfgbca', LEN('dfgbca')), (126, 'fd', LEN('fd')), (126, 'acgde', LEN('acgde')), (126, 'edfb', LEN('edfb')), (126, 'dgecafb', LEN('dgecafb')),
 (127, 'fedagb', LEN('fedagb')), (127, 'fca', LEN('fca')), (127, 'cdagf', LEN('cdagf')), (127, 'gadfe', LEN('gadfe')), (127, 'cfedag', LEN('cfedag')), (127, 'geabdcf', LEN('geabdcf')), (127, 'cegbaf', LEN('cegbaf')), (127, 'caed', LEN('caed')), (127, 'ca', LEN('ca')), (127, 'dbgfc', LEN('dbgfc')),
 (128, 'fbadge', LEN('fbadge')), (128, 'aebfcgd', LEN('aebfcgd')), (128, 'afce', LEN('afce')), (128, 'becda', LEN('becda')), (128, 'deabf', LEN('deabf')), (128, 'ec', LEN('ec')), (128, 'bagdc', LEN('bagdc')), (128, 'cde', LEN('cde')), (128, 'bcdefa', LEN('bcdefa')), (128, 'bdefcg', LEN('bdefcg')),
 (129, 'eb', LEN('eb')), (129, 'egba', LEN('egba')), (129, 'fdaec', LEN('fdaec')), (129, 'adebf', LEN('adebf')), (129, 'gcbdfa', LEN('gcbdfa')), (129, 'edgabf', LEN('edgabf')), (129, 'bgcfaed', LEN('bgcfaed')), (129, 'cbdgfe', LEN('cbdgfe')), (129, 'bed', LEN('bed')), (129, 'bafgd', LEN('bafgd')),
 (130, 'badgefc', LEN('badgefc')), (130, 'dbe', LEN('dbe')), (130, 'gcfde', LEN('gcfde')), (130, 'bd', LEN('bd')), (130, 'dabf', LEN('dabf')), (130, 'dgeacb', LEN('dgeacb')), (130, 'egbacf', LEN('egbacf')), (130, 'ebfag', LEN('ebfag')), (130, 'begdf', LEN('begdf')), (130, 'fgeabd', LEN('fgeabd')),
 (131, 'agfdce', LEN('agfdce')), (131, 'gaebd', LEN('gaebd')), (131, 'bdcaegf', LEN('bdcaegf')), (131, 'aedgc', LEN('aedgc')), (131, 'abd', LEN('abd')), (131, 'eabcfd', LEN('eabcfd')), (131, 'cdbgae', LEN('cdbgae')), (131, 'febga', LEN('febga')), (131, 'gcdb', LEN('gcdb')), (131, 'db', LEN('db')),
 (132, 'bcd', LEN('bcd')), (132, 'fdab', LEN('fdab')), (132, 'adbgfc', LEN('adbgfc')), (132, 'acdgf', LEN('acdgf')), (132, 'fdbcgea', LEN('fdbcgea')), (132, 'bd', LEN('bd')), (132, 'fcbdg', LEN('fcbdg')), (132, 'begcf', LEN('begcf')), (132, 'ecgbad', LEN('ecgbad')), (132, 'acdfge', LEN('acdfge')),
 (133, 'abfge', LEN('abfge')), (133, 'bfd', LEN('bfd')), (133, 'df', LEN('df')), (133, 'efgabcd', LEN('efgabcd')), (133, 'cbefda', LEN('cbefda')), (133, 'bfdga', LEN('bfdga')), (133, 'cgfbea', LEN('cgfbea')), (133, 'adefbg', LEN('adefbg')), (133, 'acgbd', LEN('acgbd')), (133, 'edgf', LEN('edgf')),
 (134, 'dbacgfe', LEN('dbacgfe')), (134, 'dgeca', LEN('dgeca')), (134, 'efbcg', LEN('efbcg')), (134, 'bceadg', LEN('bceadg')), (134, 'eafdbg', LEN('eafdbg')), (134, 'aeb', LEN('aeb')), (134, 'agcdef', LEN('agcdef')), (134, 'acbd', LEN('acbd')), (134, 'ab', LEN('ab')), (134, 'cebag', LEN('cebag')),
 (135, 'edcbgf', LEN('edcbgf')), (135, 'cadbef', LEN('cadbef')), (135, 'egb', LEN('egb')), (135, 'acfeb', LEN('acfeb')), (135, 'bg', LEN('bg')), (135, 'geadf', LEN('geadf')), (135, 'aefgbc', LEN('aefgbc')), (135, 'gbfea', LEN('gbfea')), (135, 'dgcfeab', LEN('dgcfeab')), (135, 'acbg', LEN('acbg')),
 (136, 'ca', LEN('ca')), (136, 'dafgb', LEN('dafgb')), (136, 'cgda', LEN('cgda')), (136, 'cabfd', LEN('cabfd')), (136, 'dacgfeb', LEN('dacgfeb')), (136, 'edfbc', LEN('edfbc')), (136, 'bca', LEN('bca')), (136, 'fdcbag', LEN('fdcbag')), (136, 'dgeabf', LEN('dgeabf')), (136, 'afecgb', LEN('afecgb')),
 (137, 'abfgd', LEN('abfgd')), (137, 'ecgdafb', LEN('ecgdafb')), (137, 'dbegaf', LEN('dbegaf')), (137, 'afdgcb', LEN('afdgcb')), (137, 'bc', LEN('bc')), (137, 'cfb', LEN('cfb')), (137, 'gcabf', LEN('gcabf')), (137, 'bcda', LEN('bcda')), (137, 'dfgceb', LEN('dfgceb')), (137, 'eacgf', LEN('eacgf')),
 (138, 'bdeag', LEN('bdeag')), (138, 'ba', LEN('ba')), (138, 'dfbge', LEN('dfbge')), (138, 'dabegc', LEN('dabegc')), (138, 'cbag', LEN('cbag')), (138, 'gabdefc', LEN('gabdefc')), (138, 'dab', LEN('dab')), (138, 'ecagd', LEN('ecagd')), (138, 'dafecb', LEN('dafecb')), (138, 'cafgde', LEN('cafgde')),
 (139, 'abgfdc', LEN('abgfdc')), (139, 'gcfbdea', LEN('gcfbdea')), (139, 'bafdc', LEN('bafdc')), (139, 'bedagf', LEN('bedagf')), (139, 'dbecag', LEN('dbecag')), (139, 'fgbc', LEN('fgbc')), (139, 'afedc', LEN('afedc')), (139, 'fb', LEN('fb')), (139, 'bfd', LEN('bfd')), (139, 'abgcd', LEN('abgcd')),
 (140, 'cbed', LEN('cbed')), (140, 'bgcefda', LEN('bgcefda')), (140, 'acgbfd', LEN('acgbfd')), (140, 'de', LEN('de')), (140, 'cdbeag', LEN('cdbeag')), (140, 'ebagd', LEN('ebagd')), (140, 'bgcda', LEN('bgcda')), (140, 'gabfe', LEN('gabfe')), (140, 'dacgfe', LEN('dacgfe')), (140, 'aed', LEN('aed')),
 (141, 'cegfbda', LEN('cegfbda')), (141, 'gbed', LEN('gbed')), (141, 'acfged', LEN('acfged')), (141, 'gdecfb', LEN('gdecfb')), (141, 'gdc', LEN('gdc')), (141, 'cfdgb', LEN('cfdgb')), (141, 'dg', LEN('dg')), (141, 'ebfdc', LEN('ebfdc')), (141, 'bfedac', LEN('bfedac')), (141, 'gfcba', LEN('gfcba')),
 (142, 'egfbc', LEN('egfbc')), (142, 'dfae', LEN('dfae')), (142, 'cafged', LEN('cafged')), (142, 'dagecb', LEN('dagecb')), (142, 'deg', LEN('deg')), (142, 'fgdca', LEN('fgdca')), (142, 'caegfbd', LEN('caegfbd')), (142, 'dcefg', LEN('dcefg')), (142, 'adcgbf', LEN('adcgbf')), (142, 'de', LEN('de')),
 (143, 'ae', LEN('ae')), (143, 'gedfba', LEN('gedfba')), (143, 'bcagd', LEN('bcagd')), (143, 'age', LEN('age')), (143, 'becgf', LEN('becgf')), (143, 'acbge', LEN('acbge')), (143, 'afbgcd', LEN('afbgcd')), (143, 'gdfebca', LEN('gdfebca')), (143, 'agdbce', LEN('agdbce')), (143, 'ceda', LEN('ceda')),
 (144, 'cfdbea', LEN('cfdbea')), (144, 'ebafc', LEN('ebafc')), (144, 'fbdea', LEN('fbdea')), (144, 'bagcf', LEN('bagcf')), (144, 'bedagf', LEN('bedagf')), (144, 'dcae', LEN('dcae')), (144, 'cgdefb', LEN('cgdefb')), (144, 'cfdeagb', LEN('cfdeagb')), (144, 'ec', LEN('ec')), (144, 'ceb', LEN('ceb')),
 (145, 'cfed', LEN('cfed')), (145, 'fca', LEN('fca')), (145, 'bcgafd', LEN('bcgafd')), (145, 'gfaedbc', LEN('gfaedbc')), (145, 'gfdae', LEN('gfdae')), (145, 'gcfae', LEN('gcfae')), (145, 'ebgfda', LEN('ebgfda')), (145, 'aebgc', LEN('aebgc')), (145, 'fc', LEN('fc')), (145, 'gdafec', LEN('gdafec')),
 (146, 'ecgbdf', LEN('ecgbdf')), (146, 'debga', LEN('debga')), (146, 'cbegd', LEN('cbegd')), (146, 'bgcfdea', LEN('bgcfdea')), (146, 'aeg', LEN('aeg')), (146, 'deafgc', LEN('deafgc')), (146, 'dfgab', LEN('dfgab')), (146, 'cabe', LEN('cabe')), (146, 'ea', LEN('ea')), (146, 'gcabed', LEN('gcabed')),
 (147, 'dbcgf', LEN('dbcgf')), (147, 'cfgeab', LEN('cfgeab')), (147, 'afedcgb', LEN('afedcgb')), (147, 'cgabd', LEN('cgabd')), (147, 'ad', LEN('ad')), (147, 'fgdeba', LEN('fgdeba')), (147, 'bad', LEN('bad')), (147, 'adec', LEN('adec')), (147, 'ecbag', LEN('ecbag')), (147, 'edgcab', LEN('edgcab')),
 (148, 'bdeacf', LEN('bdeacf')), (148, 'acf', LEN('acf')), (148, 'cfebdga', LEN('cfebdga')), (148, 'abfdg', LEN('abfdg')), (148, 'dcfe', LEN('dcfe')), (148, 'fabcge', LEN('fabcge')), (148, 'cf', LEN('cf')), (148, 'abcdge', LEN('abcdge')), (148, 'facdb', LEN('facdb')), (148, 'ecdba', LEN('ecdba')),
 (149, 'bdfaeg', LEN('bdfaeg')), (149, 'gbdafec', LEN('gbdafec')), (149, 'becad', LEN('becad')), (149, 'gebf', LEN('gebf')), (149, 'fcaegd', LEN('fcaegd')), (149, 'feagd', LEN('feagd')), (149, 'bedfa', LEN('bedfa')), (149, 'fcdagb', LEN('fcdagb')), (149, 'dfb', LEN('dfb')), (149, 'fb', LEN('fb'))
 
  INSERT INTO @input VALUES
 (150, 'aegcd', LEN('aegcd')), (150, 'gefab', LEN('gefab')), (150, 'gfadcb', LEN('gfadcb')), (150, 'dbegcfa', LEN('dbegcfa')), (150, 'fgeacb', LEN('fgeacb')), (150, 'db', LEN('db')), (150, 'bgd', LEN('bgd')), (150, 'bagde', LEN('bagde')), (150, 'bedf', LEN('bedf')), (150, 'agfdbe', LEN('agfdbe')),
 (151, 'cea', LEN('cea')), (151, 'cagf', LEN('cagf')), (151, 'befca', LEN('befca')), (151, 'gefacdb', LEN('gefacdb')), (151, 'gdaceb', LEN('gdaceb')), (151, 'febdag', LEN('febdag')), (151, 'ecdbf', LEN('ecdbf')), (151, 'ceagfb', LEN('ceagfb')), (151, 'ca', LEN('ca')), (151, 'febga', LEN('febga')),
 (152, 'eabcdf', LEN('eabcdf')), (152, 'dagfc', LEN('dagfc')), (152, 'fegdbac', LEN('fegdbac')), (152, 'acgedb', LEN('acgedb')), (152, 'dae', LEN('dae')), (152, 'ed', LEN('ed')), (152, 'geacb', LEN('geacb')), (152, 'edgb', LEN('edgb')), (152, 'adecg', LEN('adecg')), (152, 'efcgab', LEN('efcgab')),
 (153, 'fbadecg', LEN('fbadecg')), (153, 'bcedf', LEN('bcedf')), (153, 'afbdec', LEN('afbdec')), (153, 'af', LEN('af')), (153, 'fcdegb', LEN('fcdegb')), (153, 'dbaf', LEN('dbaf')), (153, 'caf', LEN('caf')), (153, 'adefc', LEN('adefc')), (153, 'facbge', LEN('facbge')), (153, 'edcga', LEN('edcga')),
 (154, 'dgefacb', LEN('dgefacb')), (154, 'gbfdca', LEN('gbfdca')), (154, 'fecbag', LEN('fecbag')), (154, 'egb', LEN('egb')), (154, 'bcgead', LEN('bcgead')), (154, 'gcfe', LEN('gcfe')), (154, 'ebfad', LEN('ebfad')), (154, 'afcgb', LEN('afcgb')), (154, 'gbeaf', LEN('gbeaf')), (154, 'eg', LEN('eg')),
 (155, 'efacb', LEN('efacb')), (155, 'eg', LEN('eg')), (155, 'gcfe', LEN('gcfe')), (155, 'gdbfa', LEN('gdbfa')), (155, 'cbeagf', LEN('cbeagf')), (155, 'bgfae', LEN('bgfae')), (155, 'fcebda', LEN('fcebda')), (155, 'gbaecd', LEN('gbaecd')), (155, 'afdebgc', LEN('afdebgc')), (155, 'age', LEN('age')),
 (156, 'cegfdb', LEN('cegfdb')), (156, 'gdbef', LEN('gdbef')), (156, 'da', LEN('da')), (156, 'adf', LEN('adf')), (156, 'bdga', LEN('bdga')), (156, 'gedafb', LEN('gedafb')), (156, 'dbeafc', LEN('dbeafc')), (156, 'fadge', LEN('fadge')), (156, 'geafc', LEN('geafc')), (156, 'dgafebc', LEN('dgafebc')),
 (157, 'fbcdg', LEN('fbcdg')), (157, 'ce', LEN('ce')), (157, 'ebgcaf', LEN('ebgcaf')), (157, 'eacb', LEN('eacb')), (157, 'ebcgf', LEN('ebcgf')), (157, 'gaefbdc', LEN('gaefbdc')), (157, 'fec', LEN('fec')), (157, 'edgbaf', LEN('edgbaf')), (157, 'gafced', LEN('gafced')), (157, 'gbafe', LEN('gbafe')),
 (158, 'dcabgf', LEN('dcabgf')), (158, 'geafc', LEN('geafc')), (158, 'gdcef', LEN('gdcef')), (158, 'fbea', LEN('fbea')), (158, 'bgadec', LEN('bgadec')), (158, 'fgcabe', LEN('fgcabe')), (158, 'af', LEN('af')), (158, 'fga', LEN('fga')), (158, 'egcfbad', LEN('egcfbad')), (158, 'ceabg', LEN('ceabg')),
 (159, 'af', LEN('af')), (159, 'bcgefd', LEN('bcgefd')), (159, 'bfedc', LEN('bfedc')), (159, 'cbadef', LEN('cbadef')), (159, 'fceba', LEN('fceba')), (159, 'fca', LEN('fca')), (159, 'gaebc', LEN('gaebc')), (159, 'edfa', LEN('edfa')), (159, 'fgacdb', LEN('fgacdb')), (159, 'dgefcba', LEN('dgefcba')),
 (160, 'caf', LEN('caf')), (160, 'debac', LEN('debac')), (160, 'cfabedg', LEN('cfabedg')), (160, 'dbfcg', LEN('dbfcg')), (160, 'gbaf', LEN('gbaf')), (160, 'af', LEN('af')), (160, 'gdcefb', LEN('gdcefb')), (160, 'edagfc', LEN('edagfc')), (160, 'fbcdag', LEN('fbcdag')), (160, 'fcadb', LEN('fcadb')),
 (161, 'fcedag', LEN('fcedag')), (161, 'gfabcd', LEN('gfabcd')), (161, 'fceagbd', LEN('fceagbd')), (161, 'dabefc', LEN('dabefc')), (161, 'gdc', LEN('gdc')), (161, 'cg', LEN('cg')), (161, 'ebdfg', LEN('ebdfg')), (161, 'bcag', LEN('bcag')), (161, 'cgdbf', LEN('cgdbf')), (161, 'cdfab', LEN('cdfab')),
 (162, 'ebcdgfa', LEN('ebcdgfa')), (162, 'bc', LEN('bc')), (162, 'defbc', LEN('defbc')), (162, 'fdbcge', LEN('fdbcge')), (162, 'cgdb', LEN('cgdb')), (162, 'febadg', LEN('febadg')), (162, 'abgcef', LEN('abgcef')), (162, 'bce', LEN('bce')), (162, 'efgbd', LEN('efgbd')), (162, 'eadcf', LEN('eadcf')),
 (163, 'gcfdab', LEN('gcfdab')), (163, 'bad', LEN('bad')), (163, 'fdbace', LEN('fdbace')), (163, 'fcbde', LEN('fcbde')), (163, 'adfe', LEN('adfe')), (163, 'daecb', LEN('daecb')), (163, 'agecdbf', LEN('agecdbf')), (163, 'aebgc', LEN('aebgc')), (163, 'ad', LEN('ad')), (163, 'bfdgec', LEN('bfdgec')),
 (164, 'bdega', LEN('bdega')), (164, 'decgafb', LEN('decgafb')), (164, 'efg', LEN('efg')), (164, 'dbcfae', LEN('dbcfae')), (164, 'baegf', LEN('baegf')), (164, 'bgfc', LEN('bgfc')), (164, 'gf', LEN('gf')), (164, 'fabec', LEN('fabec')), (164, 'gacfeb', LEN('gacfeb')), (164, 'fcdaeg', LEN('fcdaeg')),
 (165, 'dfebc', LEN('dfebc')), (165, 'efd', LEN('efd')), (165, 'defbag', LEN('defbag')), (165, 'cebda', LEN('cebda')), (165, 'df', LEN('df')), (165, 'fgeacb', LEN('fgeacb')), (165, 'fgdbeac', LEN('fgdbeac')), (165, 'fdcg', LEN('fdcg')), (165, 'becgdf', LEN('becgdf')), (165, 'ebfcg', LEN('ebfcg')),
 (166, 'aefg', LEN('aefg')), (166, 'bcagd', LEN('bcagd')), (166, 'cegfadb', LEN('cegfadb')), (166, 'ge', LEN('ge')), (166, 'aecfbg', LEN('aecfbg')), (166, 'ecagb', LEN('ecagb')), (166, 'bfaec', LEN('bfaec')), (166, 'egcfdb', LEN('egcfdb')), (166, 'abfedc', LEN('abfedc')), (166, 'geb', LEN('geb')),
 (167, 'cgbfad', LEN('cgbfad')), (167, 'ecafgd', LEN('ecafgd')), (167, 'eg', LEN('eg')), (167, 'bagdc', LEN('bagdc')), (167, 'gde', LEN('gde')), (167, 'gcbe', LEN('gcbe')), (167, 'bdfea', LEN('bdfea')), (167, 'edgab', LEN('edgab')), (167, 'eadbcg', LEN('eadbcg')), (167, 'facdbge', LEN('facdbge')),
 (168, 'gbacde', LEN('gbacde')), (168, 'adcbgf', LEN('adcbgf')), (168, 'fcadb', LEN('fcadb')), (168, 'dgefb', LEN('dgefb')), (168, 'fedba', LEN('fedba')), (168, 'cbfaegd', LEN('cbfaegd')), (168, 'ae', LEN('ae')), (168, 'daefbc', LEN('daefbc')), (168, 'cafe', LEN('cafe')), (168, 'abe', LEN('abe')),
 (169, 'cegfd', LEN('cegfd')), (169, 'aegcd', LEN('aegcd')), (169, 'dcfbeg', LEN('dcfbeg')), (169, 'ecfbad', LEN('ecfbad')), (169, 'da', LEN('da')), (169, 'agfd', LEN('agfd')), (169, 'bgcae', LEN('bgcae')), (169, 'dfacge', LEN('dfacge')), (169, 'dac', LEN('dac')), (169, 'cedgabf', LEN('cedgabf')),
 (170, 'fbcead', LEN('fbcead')), (170, 'ec', LEN('ec')), (170, 'cbef', LEN('cbef')), (170, 'dgfabe', LEN('dgfabe')), (170, 'efdac', LEN('efdac')), (170, 'dbaef', LEN('dbaef')), (170, 'ecadfbg', LEN('ecadfbg')), (170, 'ecadbg', LEN('ecadbg')), (170, 'ecd', LEN('ecd')), (170, 'gfacd', LEN('gfacd')),
 (171, 'acbg', LEN('acbg')), (171, 'gdbaf', LEN('gdbaf')), (171, 'bfc', LEN('bfc')), (171, 'edgcf', LEN('edgcf')), (171, 'fgdabc', LEN('fgdabc')), (171, 'badfce', LEN('badfce')), (171, 'dabgef', LEN('dabgef')), (171, 'cb', LEN('cb')), (171, 'cafdgbe', LEN('cafdgbe')), (171, 'fgcdb', LEN('fgcdb')),
 (172, 'fge', LEN('fge')), (172, 'ebcfag', LEN('ebcfag')), (172, 'abge', LEN('abge')), (172, 'abgfc', LEN('abgfc')), (172, 'gaecf', LEN('gaecf')), (172, 'dgfbeac', LEN('dgfbeac')), (172, 'fgbecd', LEN('fgbecd')), (172, 'cfead', LEN('cfead')), (172, 'ge', LEN('ge')), (172, 'dfagbc', LEN('dfagbc')),
 (173, 'adgefc', LEN('adgefc')), (173, 'bfde', LEN('bfde')), (173, 'fcbga', LEN('fcbga')), (173, 'eab', LEN('eab')), (173, 'fcadeb', LEN('fcadeb')), (173, 'be', LEN('be')), (173, 'acedf', LEN('acedf')), (173, 'gbaedc', LEN('gbaedc')), (173, 'gfbcead', LEN('gfbcead')), (173, 'fbcae', LEN('fbcae')),
 (174, 'afegbcd', LEN('afegbcd')), (174, 'efagd', LEN('efagd')), (174, 'gbcaef', LEN('gbcaef')), (174, 'fedc', LEN('fedc')), (174, 'dfcage', LEN('dfcage')), (174, 'ef', LEN('ef')), (174, 'cadfg', LEN('cadfg')), (174, 'fge', LEN('fge')), (174, 'fdgcba', LEN('fdgcba')), (174, 'egdba', LEN('egdba')),
 (175, 'ca', LEN('ca')), (175, 'eac', LEN('eac')), (175, 'cfade', LEN('cfade')), (175, 'dcfeg', LEN('dcfeg')), (175, 'agfc', LEN('agfc')), (175, 'cbfged', LEN('cbfged')), (175, 'gbaecd', LEN('gbaecd')), (175, 'fdcebga', LEN('fdcebga')), (175, 'abfde', LEN('abfde')), (175, 'fceagd', LEN('fceagd')),
 (176, 'fgbcad', LEN('fgbcad')), (176, 'baedgc', LEN('baedgc')), (176, 'bdgeaf', LEN('bdgeaf')), (176, 'agedb', LEN('agedb')), (176, 'eadgc', LEN('eadgc')), (176, 'gcfedba', LEN('gcfedba')), (176, 'acd', LEN('acd')), (176, 'gafec', LEN('gafec')), (176, 'dc', LEN('dc')), (176, 'bdec', LEN('bdec')),
 (177, 'bgdcaf', LEN('bgdcaf')), (177, 'ecbg', LEN('ecbg')), (177, 'acfbe', LEN('acfbe')), (177, 'eb', LEN('eb')), (177, 'gfbca', LEN('gfbca')), (177, 'facde', LEN('facde')), (177, 'fecagb', LEN('fecagb')), (177, 'gbfade', LEN('gbfade')), (177, 'gefbdca', LEN('gefbdca')), (177, 'abe', LEN('abe')),
 (178, 'bcgeaf', LEN('bcgeaf')), (178, 'bgcdfe', LEN('bgcdfe')), (178, 'egbdf', LEN('egbdf')), (178, 'fbc', LEN('fbc')), (178, 'gcdfb', LEN('gcdfb')), (178, 'cf', LEN('cf')), (178, 'fdgbcea', LEN('fdgbcea')), (178, 'decf', LEN('decf')), (178, 'bgcad', LEN('bgcad')), (178, 'defgab', LEN('defgab')),
 (179, 'bg', LEN('bg')), (179, 'bga', LEN('bga')), (179, 'acgfdbe', LEN('acgfdbe')), (179, 'gdeb', LEN('gdeb')), (179, 'abgce', LEN('abgce')), (179, 'bfcadg', LEN('bfcadg')), (179, 'efcbda', LEN('efcbda')), (179, 'cdeab', LEN('cdeab')), (179, 'fcaeg', LEN('fcaeg')), (179, 'adcegb', LEN('adcegb')),
 (180, 'bg', LEN('bg')), (180, 'egfcb', LEN('egfcb')), (180, 'gcebdf', LEN('gcebdf')), (180, 'ebg', LEN('ebg')), (180, 'egcfd', LEN('egcfd')), (180, 'abdfeg', LEN('abdfeg')), (180, 'cdefgab', LEN('cdefgab')), (180, 'dcgb', LEN('dcgb')), (180, 'cabfe', LEN('cabfe')), (180, 'gefacd', LEN('gefacd')),
 (181, 'gdefbc', LEN('gdefbc')), (181, 'gcedf', LEN('gcedf')), (181, 'dcaf', LEN('dcaf')), (181, 'aedgb', LEN('aedgb')), (181, 'dcfgaeb', LEN('dcfgaeb')), (181, 'gdacef', LEN('gdacef')), (181, 'fa', LEN('fa')), (181, 'fbaecg', LEN('fbaecg')), (181, 'eaf', LEN('eaf')), (181, 'afdge', LEN('afdge')),
 (182, 'debc', LEN('debc')), (182, 'dbfgc', LEN('dbfgc')), (182, 'edgbcf', LEN('edgbcf')), (182, 'fgceb', LEN('fgceb')), (182, 'egacbf', LEN('egacbf')), (182, 'gdfac', LEN('gdfac')), (182, 'gdecbfa', LEN('gdecbfa')), (182, 'begdaf', LEN('begdaf')), (182, 'db', LEN('db')), (182, 'dgb', LEN('dgb')),
 (183, 'bgce', LEN('bgce')), (183, 'bdcafge', LEN('bdcafge')), (183, 'eb', LEN('eb')), (183, 'fadec', LEN('fadec')), (183, 'edacbg', LEN('edacbg')), (183, 'bdfgac', LEN('bdfgac')), (183, 'cbgad', LEN('cbgad')), (183, 'fegbda', LEN('fegbda')), (183, 'aeb', LEN('aeb')), (183, 'cebda', LEN('cebda')),
 (184, 'fd', LEN('fd')), (184, 'edf', LEN('edf')), (184, 'gcfae', LEN('gcfae')), (184, 'gabed', LEN('gabed')), (184, 'dabf', LEN('dabf')), (184, 'ebdcagf', LEN('ebdcagf')), (184, 'eadgf', LEN('eadgf')), (184, 'dfcgeb', LEN('dfcgeb')), (184, 'gedfab', LEN('gedfab')), (184, 'degbac', LEN('degbac')),
 (185, 'agbef', LEN('agbef')), (185, 'aebcfg', LEN('aebcfg')), (185, 'cegfb', LEN('cegfb')), (185, 'ba', LEN('ba')), (185, 'adfeg', LEN('adfeg')), (185, 'bgac', LEN('bgac')), (185, 'fdbcea', LEN('fdbcea')), (185, 'ebcadgf', LEN('ebcadgf')), (185, 'bea', LEN('bea')), (185, 'gcdfeb', LEN('gcdfeb')),
 (186, 'gdbeca', LEN('gdbeca')), (186, 'beadc', LEN('beadc')), (186, 'eagb', LEN('eagb')), (186, 'ecdgb', LEN('ecdgb')), (186, 'cefdbg', LEN('cefdbg')), (186, 'adefbgc', LEN('adefbgc')), (186, 'fedgac', LEN('fedgac')), (186, 'aec', LEN('aec')), (186, 'ae', LEN('ae')), (186, 'dfacb', LEN('dfacb')),
 (187, 'egfdb', LEN('egfdb')), (187, 'ebgcda', LEN('ebgcda')), (187, 'ceadbfg', LEN('ceadbfg')), (187, 'cfdgea', LEN('cfdgea')), (187, 'aeb', LEN('aeb')), (187, 'ba', LEN('ba')), (187, 'cbegaf', LEN('cbegaf')), (187, 'agbef', LEN('agbef')), (187, 'cfage', LEN('cfage')), (187, 'cbfa', LEN('cbfa')),
 (188, 'fbaecgd', LEN('fbaecgd')), (188, 'bdafc', LEN('bdafc')), (188, 'dcgbf', LEN('dcgbf')), (188, 'fgc', LEN('fgc')), (188, 'bgca', LEN('bgca')), (188, 'cg', LEN('cg')), (188, 'fcbgda', LEN('fcbgda')), (188, 'gfdbe', LEN('gfdbe')), (188, 'fadbec', LEN('fadbec')), (188, 'gadcfe', LEN('gadcfe')),
 (189, 'ge', LEN('ge')), (189, 'gbced', LEN('gbced')), (189, 'efabgd', LEN('efabgd')), (189, 'dbagec', LEN('dbagec')), (189, 'gbe', LEN('gbe')), (189, 'agce', LEN('agce')), (189, 'agbdcf', LEN('agbdcf')), (189, 'dbcef', LEN('dbcef')), (189, 'cgfaedb', LEN('cgfaedb')), (189, 'abcdg', LEN('abcdg')),
 (190, 'dcafbg', LEN('dcafbg')), (190, 'cfegdb', LEN('cfegdb')), (190, 'gfdeb', LEN('gfdeb')), (190, 'dbegaf', LEN('dbegaf')), (190, 'fab', LEN('fab')), (190, 'abcedfg', LEN('abcedfg')), (190, 'gbae', LEN('gbae')), (190, 'fdaec', LEN('fdaec')), (190, 'adbfe', LEN('adbfe')), (190, 'ba', LEN('ba')),
 (191, 'gfe', LEN('gfe')), (191, 'fcbe', LEN('fcbe')), (191, 'bgdfce', LEN('bgdfce')), (191, 'gcdbe', LEN('gcdbe')), (191, 'gedbf', LEN('gedbf')), (191, 'cadegb', LEN('cadegb')), (191, 'ceagbfd', LEN('ceagbfd')), (191, 'cadfge', LEN('cadfge')), (191, 'ef', LEN('ef')), (191, 'gdbfa', LEN('gdbfa')),
 (192, 'bdcfae', LEN('bdcfae')), (192, 'fbecd', LEN('fbecd')), (192, 'ecgdab', LEN('ecgdab')), (192, 'afcd', LEN('afcd')), (192, 'acefb', LEN('acefb')), (192, 'edgfcb', LEN('edgfcb')), (192, 'acb', LEN('acb')), (192, 'ca', LEN('ca')), (192, 'abfdceg', LEN('abfdceg')), (192, 'egafb', LEN('egafb')),
 (193, 'dacb', LEN('dacb')), (193, 'edfba', LEN('edfba')), (193, 'cdbgeaf', LEN('cdbgeaf')), (193, 'eadfg', LEN('eadfg')), (193, 'ecgfbd', LEN('ecgfbd')), (193, 'db', LEN('db')), (193, 'ecabgf', LEN('ecabgf')), (193, 'ceadbf', LEN('ceadbf')), (193, 'acebf', LEN('acebf')), (193, 'bfd', LEN('bfd')),
 (194, 'cdabe', LEN('cdabe')), (194, 'edfgca', LEN('edfgca')), (194, 'cgefb', LEN('cgefb')), (194, 'cfabed', LEN('cfabed')), (194, 'cfdbe', LEN('cfdbe')), (194, 'cfd', LEN('cfd')), (194, 'edabgc', LEN('edabgc')), (194, 'ecafbgd', LEN('ecafbgd')), (194, 'dfab', LEN('dfab')), (194, 'fd', LEN('fd')),
 (195, 'dcgbe', LEN('dcgbe')), (195, 'gdfeab', LEN('gdfeab')), (195, 'efca', LEN('efca')), (195, 'gbdacf', LEN('gbdacf')), (195, 'fcedb', LEN('fcedb')), (195, 'fcd', LEN('fcd')), (195, 'efadcb', LEN('efadcb')), (195, 'dbefa', LEN('dbefa')), (195, 'fc', LEN('fc')), (195, 'cegbdfa', LEN('cegbdfa')),
 (196, 'cdbfage', LEN('cdbfage')), (196, 'fadc', LEN('fadc')), (196, 'bdefga', LEN('bdefga')), (196, 'cafegb', LEN('cafegb')), (196, 'dag', LEN('dag')), (196, 'facgb', LEN('facgb')), (196, 'da', LEN('da')), (196, 'ebcgd', LEN('ebcgd')), (196, 'gabcd', LEN('gabcd')), (196, 'abcdgf', LEN('abcdgf')),
 (197, 'cfgedba', LEN('cfgedba')), (197, 'gdafec', LEN('gdafec')), (197, 'gafdb', LEN('gafdb')), (197, 'fecb', LEN('fecb')), (197, 'aedcbf', LEN('aedcbf')), (197, 'cbead', LEN('cbead')), (197, 'deagbc', LEN('deagbc')), (197, 'adfbc', LEN('adfbc')), (197, 'dfc', LEN('dfc')), (197, 'fc', LEN('fc')),
 (198, 'gdea', LEN('gdea')), (198, 'gdafbc', LEN('gdafbc')), (198, 'dfebc', LEN('dfebc')), (198, 'gefdc', LEN('gefdc')), (198, 'feg', LEN('feg')), (198, 'ge', LEN('ge')), (198, 'gfceda', LEN('gfceda')), (198, 'cfdga', LEN('cfdga')), (198, 'fabegc', LEN('fabegc')), (198, 'cbgfead', LEN('cbgfead')),
 (199, 'adbfg', LEN('adbfg')), (199, 'ebcfg', LEN('ebcfg')), (199, 'cdbafe', LEN('cdbafe')), (199, 'acfbdeg', LEN('acfbdeg')), (199, 'cgea', LEN('cgea')), (199, 'gaefb', LEN('gaefb')), (199, 'dgbcfe', LEN('dgbcfe')), (199, 'bea', LEN('bea')), (199, 'bcafge', LEN('bcafge')), (199, 'ae', LEN('ae')),
 (200, 'dcfaeg', LEN('dcfaeg')), (200, 'dcfbag', LEN('dcfbag')), (200, 'gfcdeba', LEN('gfcdeba')), (200, 'fagb', LEN('fagb')), (200, 'dgacb', LEN('dgacb')), (200, 'fgc', LEN('fgc')), (200, 'cedbf', LEN('cedbf')), (200, 'fcgdb', LEN('fcgdb')), (200, 'dbacge', LEN('dbacge')), (200, 'gf', LEN('gf'))

INSERT INTO @output VALUES
 
 (1,'ecagd', LEN('ecagd')),(1,'gcbde', LEN('gcbde')),(1,'dbcefa', LEN('dbcefa')),(1,'bgfd', LEN('bgfd')),
(2,'gcbef', LEN('gcbef')),(2,'befcg', LEN('befcg')),(2,'ac', LEN('ac')),(2,'ac', LEN('ac')),
(3,'adbgef', LEN('adbgef')),(3,'dfgbe', LEN('dfgbe')),(3,'dbgfe', LEN('dbgfe')),(3,'agdfb', LEN('agdfb')),
(4,'adfcegb', LEN('adfcegb')),(4,'dgcfabe', LEN('dgcfabe')),(4,'ea', LEN('ea')),(4,'cbfdge', LEN('cbfdge')),
(5,'ef', LEN('ef')),(5,'bdceg', LEN('bdceg')),(5,'begdafc', LEN('begdafc')),(5,'efgdc', LEN('efgdc')),
(6,'dcg', LEN('dcg')),(6,'gecdb', LEN('gecdb')),(6,'adebfg', LEN('adebfg')),(6,'cdbeg', LEN('cdbeg')),
(7,'fad', LEN('fad')),(7,'bacf', LEN('bacf')),(7,'adbgce', LEN('adbgce')),(7,'gbdafc', LEN('gbdafc')),
(8,'adbef', LEN('adbef')),(8,'gfcdeb', LEN('gfcdeb')),(8,'bdgcaf', LEN('bdgcaf')),(8,'dbegfc', LEN('dbegfc')),
(9,'bc', LEN('bc')),(9,'cbfadeg', LEN('cbfadeg')),(9,'ecfdgb', LEN('ecfdgb')),(9,'gbc', LEN('gbc')),
(10,'egafc', LEN('egafc')),(10,'fbdg', LEN('fbdg')),(10,'dabgefc', LEN('dabgefc')),(10,'agdeb', LEN('agdeb')),
(11,'eabdcf', LEN('eabdcf')),(11,'bdeafcg', LEN('bdeafcg')),(11,'acgbe', LEN('acgbe')),(11,'fceg', LEN('fceg')),
(12,'dbcag', LEN('dbcag')),(12,'cfdgb', LEN('cfdgb')),(12,'dgfcbe', LEN('dgfcbe')),(12,'gaecfb', LEN('gaecfb')),
(13,'gefbda', LEN('gefbda')),(13,'bgcfde', LEN('bgcfde')),(13,'bfc', LEN('bfc')),(13,'gadfeb', LEN('gadfeb')),
(14,'bfdca', LEN('bfdca')),(14,'bgfd', LEN('bgfd')),(14,'bgacfd', LEN('bgacfd')),(14,'gf', LEN('gf')),
(15,'ef', LEN('ef')),(15,'efdcba', LEN('efdcba')),(15,'abdfce', LEN('abdfce')),(15,'agcbf', LEN('agcbf')),
(16,'ebcagf', LEN('ebcagf')),(16,'fc', LEN('fc')),(16,'acdfbg', LEN('acdfbg')),(16,'cfdbag', LEN('cfdbag')),
(17,'becfd', LEN('becfd')),(17,'bea', LEN('bea')),(17,'acbf', LEN('acbf')),(17,'ebdgcf', LEN('ebdgcf')),
(18,'adfbe', LEN('adfbe')),(18,'badef', LEN('badef')),(18,'gdbcaf', LEN('gdbcaf')),(18,'ecfd', LEN('ecfd')),
(19,'agfced', LEN('agfced')),(19,'degafc', LEN('degafc')),(19,'bf', LEN('bf')),(19,'cbdga', LEN('cbdga')),
(20,'bfcg', LEN('bfcg')),(20,'abfdce', LEN('abfdce')),(20,'gf', LEN('gf')),(20,'bgdeaf', LEN('bgdeaf')),
(21,'dgebfa', LEN('dgebfa')),(21,'agdbe', LEN('agdbe')),(21,'gefdab', LEN('gefdab')),(21,'dgbae', LEN('dgbae')),
(22,'fbge', LEN('fbge')),(22,'fb', LEN('fb')),(22,'caedb', LEN('caedb')),(22,'fb', LEN('fb')),
(23,'ebacfdg', LEN('ebacfdg')),(23,'dbc', LEN('dbc')),(23,'cade', LEN('cade')),(23,'fgcdbea', LEN('fgcdbea')),
(24,'gfbcdae', LEN('gfbcdae')),(24,'bgecfa', LEN('bgecfa')),(24,'fgdba', LEN('fgdba')),(24,'fceag', LEN('fceag')),
(25,'bgeacd', LEN('bgeacd')),(25,'dgbeca', LEN('dgbeca')),(25,'gcdafeb', LEN('gcdafeb')),(25,'fgbace', LEN('fgbace')),
(26,'cdf', LEN('cdf')),(26,'dabfgce', LEN('dabfgce')),(26,'aecdb', LEN('aecdb')),(26,'gbafdc', LEN('gbafdc')),
(27,'cbdae', LEN('cbdae')),(27,'deabc', LEN('deabc')),(27,'agdeb', LEN('agdeb')),(27,'dcgfeab', LEN('dcgfeab')),
(28,'aced', LEN('aced')),(28,'dcea', LEN('dcea')),(28,'ecda', LEN('ecda')),(28,'cbgaf', LEN('cbgaf')),
(29,'dacfge', LEN('dacfge')),(29,'fga', LEN('fga')),(29,'gf', LEN('gf')),(29,'eadgcfb', LEN('eadgcfb')),
(30,'bcdef', LEN('bcdef')),(30,'dcfbea', LEN('dcfbea')),(30,'dfgb', LEN('dfgb')),(30,'degcf', LEN('degcf')),
(31,'gbeadc', LEN('gbeadc')),(31,'edgabc', LEN('edgabc')),(31,'aedg', LEN('aedg')),(31,'fcbegad', LEN('fcbegad')),
(32,'ba', LEN('ba')),(32,'bdga', LEN('bdga')),(32,'abc', LEN('abc')),(32,'ab', LEN('ab')),
(33,'cfbegda', LEN('cfbegda')),(33,'cafb', LEN('cafb')),(33,'efdbcg', LEN('efdbcg')),(33,'bagecd', LEN('bagecd')),
(34,'fagedbc', LEN('fagedbc')),(34,'ad', LEN('ad')),(34,'gefbda', LEN('gefbda')),(34,'dcaegb', LEN('dcaegb')),
(35,'bacgef', LEN('bacgef')),(35,'cbef', LEN('cbef')),(35,'fecb', LEN('fecb')),(35,'bac', LEN('bac')),
(36,'cagdfe', LEN('cagdfe')),(36,'gbd', LEN('gbd')),(36,'defcag', LEN('defcag')),(36,'abgedf', LEN('abgedf')),
(37,'ebgdfca', LEN('ebgdfca')),(37,'dfgaeb', LEN('dfgaeb')),(37,'bdefa', LEN('bdefa')),(37,'bga', LEN('bga')),
(38,'gaedfc', LEN('gaedfc')),(38,'ceagb', LEN('ceagb')),(38,'dfagec', LEN('dfagec')),(38,'ebfd', LEN('ebfd')),
(39,'ecf', LEN('ecf')),(39,'aecdb', LEN('aecdb')),(39,'fc', LEN('fc')),(39,'fcdbgae', LEN('fcdbgae')),
(40,'gedfb', LEN('gedfb')),(40,'bgdef', LEN('bgdef')),(40,'egbcad', LEN('egbcad')),(40,'dgb', LEN('dgb')),
(41,'afd', LEN('afd')),(41,'adf', LEN('adf')),(41,'dfcbe', LEN('dfcbe')),(41,'gcdbaf', LEN('gcdbaf')),
(42,'ebgfdca', LEN('ebgfdca')),(42,'ebdcga', LEN('ebdcga')),(42,'cfdaebg', LEN('cfdaebg')),(42,'agcef', LEN('agcef')),
(43,'abdfcg', LEN('abdfcg')),(43,'dfe', LEN('dfe')),(43,'fcgbde', LEN('fcgbde')),(43,'edf', LEN('edf')),
(44,'fagdecb', LEN('fagdecb')),(44,'dcgbafe', LEN('dcgbafe')),(44,'ceb', LEN('ceb')),(44,'adbegc', LEN('adbegc')),
(45,'ega', LEN('ega')),(45,'dgaefbc', LEN('dgaefbc')),(45,'fbgad', LEN('fbgad')),(45,'abcfge', LEN('abcfge')),
(46,'efcgbda', LEN('efcgbda')),(46,'gde', LEN('gde')),(46,'ebcga', LEN('ebcga')),(46,'gadebc', LEN('gadebc')),
(47,'bcdfeg', LEN('bcdfeg')),(47,'edbgcf', LEN('edbgcf')),(47,'gfbcd', LEN('gfbcd')),(47,'dbfcg', LEN('dbfcg')),
(48,'cafgdbe', LEN('cafgdbe')),(48,'abg', LEN('abg')),(48,'eagcdf', LEN('eagcdf')),(48,'abefgd', LEN('abefgd')),
(49,'agecf', LEN('agecf')),(49,'gdcefa', LEN('gdcefa')),(49,'abgfd', LEN('abgfd')),(49,'efagcb', LEN('efagcb')),
(50,'agebfd', LEN('agebfd')),(50,'ecbda', LEN('ecbda')),(50,'dafc', LEN('dafc')),(50,'bfedgc', LEN('bfedgc')),
(51,'bfce', LEN('bfce')),(51,'caegbd', LEN('caegbd')),(51,'gcf', LEN('gcf')),(51,'gbcdf', LEN('gbcdf')),
(52,'aegdc', LEN('aegdc')),(52,'dcebga', LEN('dcebga')),(52,'fa', LEN('fa')),(52,'fgcaebd', LEN('fgcaebd')),
(53,'eagcdfb', LEN('eagcdfb')),(53,'ecfa', LEN('ecfa')),(53,'gcf', LEN('gcf')),(53,'gbaefc', LEN('gbaefc')),
(54,'bcf', LEN('bcf')),(54,'fgabdc', LEN('fgabdc')),(54,'cabgdf', LEN('cabgdf')),(54,'cf', LEN('cf')),
(55,'dceafbg', LEN('dceafbg')),(55,'bedga', LEN('bedga')),(55,'abf', LEN('abf')),(55,'bcaged', LEN('bcaged')),
(56,'efabdg', LEN('efabdg')),(56,'gcbfd', LEN('gcbfd')),(56,'decbgf', LEN('decbgf')),(56,'cfbged', LEN('cfbged')),
(57,'cgeabd', LEN('cgeabd')),(57,'gcfdeba', LEN('gcfdeba')),(57,'ebgafcd', LEN('ebgafcd')),(57,'gcdfbea', LEN('gcdfbea')),
(58,'age', LEN('age')),(58,'fabg', LEN('fabg')),(58,'bfag', LEN('bfag')),(58,'egcdb', LEN('egcdb')),
(59,'cdf', LEN('cdf')),(59,'befgca', LEN('befgca')),(59,'bfcga', LEN('bfcga')),(59,'agbecf', LEN('agbecf')),
(60,'aec', LEN('aec')),(60,'ca', LEN('ca')),(60,'begac', LEN('begac')),(60,'fedbca', LEN('fedbca')),
(61,'edbfa', LEN('edbfa')),(61,'debfag', LEN('debfag')),(61,'bdcfe', LEN('bdcfe')),(61,'abfge', LEN('abfge')),
(62,'ebagf', LEN('ebagf')),(62,'defcba', LEN('defcba')),(62,'acfge', LEN('acfge')),(62,'afegb', LEN('afegb')),
(63,'dgabf', LEN('dgabf')),(63,'gac', LEN('gac')),(63,'agfbd', LEN('agfbd')),(63,'gdceba', LEN('gdceba')),
(64,'eb', LEN('eb')),(64,'ecb', LEN('ecb')),(64,'facdb', LEN('facdb')),(64,'dacbgf', LEN('dacbgf')),
(65,'baedgf', LEN('baedgf')),(65,'ebcfagd', LEN('ebcfagd')),(65,'cegdfb', LEN('cegdfb')),(65,'bagfcde', LEN('bagfcde')),
(66,'fbcad', LEN('fbcad')),(66,'bgfcea', LEN('bgfcea')),(66,'gefdbca', LEN('gefdbca')),(66,'ea', LEN('ea')),
(67,'fagde', LEN('fagde')),(67,'adegfbc', LEN('adegfbc')),(67,'fbaedg', LEN('fbaedg')),(67,'ageb', LEN('ageb')),
(68,'egd', LEN('egd')),(68,'fbdgec', LEN('fbdgec')),(68,'abcedf', LEN('abcedf')),(68,'cagdb', LEN('cagdb')),
(69,'bcde', LEN('bcde')),(69,'edbc', LEN('edbc')),(69,'bdgafce', LEN('bdgafce')),(69,'bfaedgc', LEN('bfaedgc')),
(70,'caf', LEN('caf')),(70,'fgda', LEN('fgda')),(70,'bcdgea', LEN('bcdgea')),(70,'cfa', LEN('cfa')),
(71,'fedbgac', LEN('fedbgac')),(71,'daefbgc', LEN('daefbgc')),(71,'gced', LEN('gced')),(71,'egbfda', LEN('egbfda')),
(72,'adbcef', LEN('adbcef')),(72,'daefc', LEN('daefc')),(72,'acdef', LEN('acdef')),(72,'ab', LEN('ab')),
(73,'ecfgad', LEN('ecfgad')),(73,'ac', LEN('ac')),(73,'ecdfga', LEN('ecdfga')),(73,'bcdgf', LEN('bcdgf')),
(74,'bgadcef', LEN('bgadcef')),(74,'ab', LEN('ab')),(74,'gcebf', LEN('gcebf')),(74,'ab', LEN('ab')),
(75,'dabgcef', LEN('dabgcef')),(75,'egfbac', LEN('egfbac')),(75,'edcgfb', LEN('edcgfb')),(75,'fcebg', LEN('fcebg')),
(76,'dacfe', LEN('dacfe')),(76,'adcfe', LEN('adcfe')),(76,'fdag', LEN('fdag')),(76,'adgf', LEN('adgf')),
(77,'ea', LEN('ea')),(77,'edgfc', LEN('edgfc')),(77,'cadge', LEN('cadge')),(77,'edabcf', LEN('edabcf')),
(78,'efgacb', LEN('efgacb')),(78,'acbedf', LEN('acbedf')),(78,'dcgeb', LEN('dcgeb')),(78,'acegb', LEN('acegb')),
(79,'gaebcd', LEN('gaebcd')),(79,'acgdefb', LEN('acgdefb')),(79,'feda', LEN('feda')),(79,'bfdga', LEN('bfdga')),
(80,'gfbdae', LEN('gfbdae')),(80,'be', LEN('be')),(80,'be', LEN('be')),(80,'ceadg', LEN('ceadg')),
(81,'abdf', LEN('abdf')),(81,'becdga', LEN('becdga')),(81,'dgefba', LEN('dgefba')),(81,'adg', LEN('adg')),
(82,'egca', LEN('egca')),(82,'gadfe', LEN('gadfe')),(82,'ce', LEN('ce')),(82,'eacg', LEN('eacg')),
(83,'edc', LEN('edc')),(83,'ced', LEN('ced')),(83,'dce', LEN('dce')),(83,'acdeb', LEN('acdeb')),
(84,'cdfe', LEN('cdfe')),(84,'cfageb', LEN('cfageb')),(84,'baefcd', LEN('baefcd')),(84,'dcgaeb', LEN('dcgaeb')),
(85,'dgfbce', LEN('dgfbce')),(85,'edafgcb', LEN('edafgcb')),(85,'cd', LEN('cd')),(85,'gdbfce', LEN('gdbfce')),
(86,'gced', LEN('gced')),(86,'dga', LEN('dga')),(86,'gfadbc', LEN('gfadbc')),(86,'gabce', LEN('gabce')),
(87,'dacfg', LEN('dacfg')),(87,'adbf', LEN('adbf')),(87,'bd', LEN('bd')),(87,'fgecda', LEN('fgecda')),
(88,'gcfa', LEN('gcfa')),(88,'ebcag', LEN('ebcag')),(88,'gbcdea', LEN('gbcdea')),(88,'efbcgda', LEN('efbcgda')),
(89,'gdbac', LEN('gdbac')),(89,'dbfgea', LEN('dbfgea')),(89,'cgefda', LEN('cgefda')),(89,'dbcag', LEN('dbcag')),
(90,'afecbg', LEN('afecbg')),(90,'cfge', LEN('cfge')),(90,'baecg', LEN('baecg')),(90,'geb', LEN('geb')),
(91,'cefbad', LEN('cefbad')),(91,'gb', LEN('gb')),(91,'gfcea', LEN('gfcea')),(91,'bg', LEN('bg')),
(92,'bdafce', LEN('bdafce')),(92,'bgc', LEN('bgc')),(92,'gbc', LEN('gbc')),(92,'gb', LEN('gb')),
(93,'dgbc', LEN('dgbc')),(93,'feadbc', LEN('feadbc')),(93,'fcdgeb', LEN('fcdgeb')),(93,'ceadfb', LEN('ceadfb')),
(94,'gcbaf', LEN('gcbaf')),(94,'cfeda', LEN('cfeda')),(94,'fegb', LEN('fegb')),(94,'gcebaf', LEN('gcebaf')),
(95,'ac', LEN('ac')),(95,'gbfea', LEN('gbfea')),(95,'dgafbc', LEN('dgafbc')),(95,'ca', LEN('ca')),
(96,'efb', LEN('efb')),(96,'aefbdg', LEN('aefbdg')),(96,'fdgecb', LEN('fdgecb')),(96,'abde', LEN('abde')),
(97,'cbd', LEN('cbd')),(97,'edgca', LEN('edgca')),(97,'badg', LEN('badg')),(97,'ecbgda', LEN('ecbgda')),
(98,'cedbagf', LEN('cedbagf')),(98,'fabd', LEN('fabd')),(98,'fbecd', LEN('fbecd')),(98,'ebafc', LEN('ebafc')),
(99,'acbdg', LEN('acbdg')),(99,'bcdfge', LEN('bcdfge')),(99,'cbgad', LEN('cbgad')),(99,'agfcbde', LEN('agfcbde')),
(100,'eaf', LEN('eaf')),(100,'fegac', LEN('fegac')),(100,'egab', LEN('egab')),(100,'fdbaec', LEN('fdbaec')),
(101,'cefdag', LEN('cefdag')),(101,'facdb', LEN('facdb')),(101,'ab', LEN('ab')),(101,'fgdbace', LEN('fgdbace')),
(102,'bdcgfae', LEN('bdcgfae')),(102,'eacdf', LEN('eacdf')),(102,'eafbc', LEN('eafbc')),(102,'begaf', LEN('begaf')),
(103,'abfec', LEN('abfec')),(103,'bacgdf', LEN('bacgdf')),(103,'bae', LEN('bae')),(103,'cdefba', LEN('cdefba')),
(104,'agebf', LEN('agebf')),(104,'cbefg', LEN('cbefg')),(104,'efbdgac', LEN('efbdgac')),(104,'afbc', LEN('afbc')),
(105,'cdgafe', LEN('cdgafe')),(105,'gfc', LEN('gfc')),(105,'dgbfac', LEN('dgbfac')),(105,'aefc', LEN('aefc')),
(106,'gbdeaf', LEN('gbdeaf')),(106,'gedacf', LEN('gedacf')),(106,'eafbgd', LEN('eafbgd')),(106,'fgdeac', LEN('fgdeac')),
(107,'cab', LEN('cab')),(107,'fdgeac', LEN('fdgeac')),(107,'bafcd', LEN('bafcd')),(107,'cab', LEN('cab')),
(108,'ec', LEN('ec')),(108,'feagd', LEN('feagd')),(108,'cagbdf', LEN('cagbdf')),(108,'bced', LEN('bced')),
(109,'fcbad', LEN('fcbad')),(109,'ecfgda', LEN('ecfgda')),(109,'defab', LEN('defab')),(109,'afebd', LEN('afebd')),
(110,'bcdafg', LEN('bcdafg')),(110,'dbg', LEN('dbg')),(110,'cadb', LEN('cadb')),(110,'bgd', LEN('bgd')),
(111,'aegcb', LEN('aegcb')),(111,'gdc', LEN('gdc')),(111,'agcefb', LEN('agcefb')),(111,'bagce', LEN('bagce')),
(112,'eg', LEN('eg')),(112,'dbeagf', LEN('dbeagf')),(112,'aecdfb', LEN('aecdfb')),(112,'ge', LEN('ge')),
(113,'gcf', LEN('gcf')),(113,'fbdc', LEN('fbdc')),(113,'fdbc', LEN('fdbc')),(113,'fgcabd', LEN('fgcabd')),
(114,'ea', LEN('ea')),(114,'ecbagf', LEN('ecbagf')),(114,'fbcgda', LEN('fbcgda')),(114,'ea', LEN('ea')),
(115,'ef', LEN('ef')),(115,'dfabge', LEN('dfabge')),(115,'cgbafed', LEN('cgbafed')),(115,'cdgfa', LEN('cdgfa')),
(116,'ace', LEN('ace')),(116,'agfcd', LEN('agfcd')),(116,'gfbedc', LEN('gfbedc')),(116,'ae', LEN('ae')),
(117,'afeg', LEN('afeg')),(117,'bcegda', LEN('bcegda')),(117,'agfcde', LEN('agfcde')),(117,'aecgdb', LEN('aecgdb')),
(118,'fc', LEN('fc')),(118,'dabfge', LEN('dabfge')),(118,'beadfg', LEN('beadfg')),(118,'defc', LEN('defc')),
(119,'bfdce', LEN('bfdce')),(119,'fdbge', LEN('fdbge')),(119,'cgfbde', LEN('cgfbde')),(119,'ebgdf', LEN('ebgdf')),
(120,'ac', LEN('ac')),(120,'ebgda', LEN('ebgda')),(120,'bgeca', LEN('bgeca')),(120,'eafc', LEN('eafc')),
(121,'fegadcb', LEN('fegadcb')),(121,'egbdac', LEN('egbdac')),(121,'aecdgb', LEN('aecdgb')),(121,'afebcg', LEN('afebcg')),
(122,'gbfeacd', LEN('gbfeacd')),(122,'bgcdfa', LEN('bgcdfa')),(122,'aebfd', LEN('aebfd')),(122,'facgbd', LEN('facgbd')),
(123,'bfagdc', LEN('bfagdc')),(123,'bc', LEN('bc')),(123,'feabcd', LEN('feabcd')),(123,'cb', LEN('cb')),
(124,'gf', LEN('gf')),(124,'fg', LEN('fg')),(124,'dfacbg', LEN('dfacbg')),(124,'fbacgde', LEN('fbacgde')),
(125,'bga', LEN('bga')),(125,'dcfageb', LEN('dcfageb')),(125,'cbaf', LEN('cbaf')),(125,'acdfeg', LEN('acdfeg')),
(126,'adecg', LEN('adecg')),(126,'eacbdf', LEN('eacbdf')),(126,'fdeb', LEN('fdeb')),(126,'fdc', LEN('fdc')),
(127,'fbcdg', LEN('fbcdg')),(127,'cdgfa', LEN('cdgfa')),(127,'agedf', LEN('agedf')),(127,'bgecdfa', LEN('bgecdfa')),
(128,'aecf', LEN('aecf')),(128,'gdaebf', LEN('gdaebf')),(128,'dce', LEN('dce')),(128,'bgdafe', LEN('bgdafe')),
(129,'dbaef', LEN('dbaef')),(129,'cabdfge', LEN('cabdfge')),(129,'faedb', LEN('faedb')),(129,'aegb', LEN('aegb')),
(130,'ebd', LEN('ebd')),(130,'cbdega', LEN('cbdega')),(130,'begdfa', LEN('begdfa')),(130,'dfabge', LEN('dfabge')),
(131,'cfebdag', LEN('cfebdag')),(131,'cbdg', LEN('cbdg')),(131,'db', LEN('db')),(131,'acbfde', LEN('acbfde')),
(132,'dfecag', LEN('dfecag')),(132,'fbad', LEN('fbad')),(132,'bgcfd', LEN('bgcfd')),(132,'dacfgb', LEN('dacfgb')),
(133,'gabfe', LEN('gabfe')),(133,'bgfea', LEN('bgfea')),(133,'fd', LEN('fd')),(133,'gdfe', LEN('gdfe')),
(134,'ecagfd', LEN('ecagfd')),(134,'ab', LEN('ab')),(134,'egdac', LEN('egdac')),(134,'cbadfge', LEN('cbadfge')),
(135,'ecfdbga', LEN('ecfdbga')),(135,'bge', LEN('bge')),(135,'decfba', LEN('decfba')),(135,'dabcef', LEN('dabcef')),
(136,'feadbg', LEN('feadbg')),(136,'bacfd', LEN('bacfd')),(136,'cafgbd', LEN('cafgbd')),(136,'cba', LEN('cba')),
(137,'cefbdag', LEN('cefbdag')),(137,'fbc', LEN('fbc')),(137,'fgbda', LEN('fgbda')),(137,'cdab', LEN('cdab')),
(138,'geadb', LEN('geadb')),(138,'ab', LEN('ab')),(138,'bgac', LEN('bgac')),(138,'ebcdfa', LEN('ebcdfa')),
(139,'dcbag', LEN('dcbag')),(139,'gfbdac', LEN('gfbdac')),(139,'bdf', LEN('bdf')),(139,'aedgfb', LEN('aedgfb')),
(140,'bedag', LEN('bedag')),(140,'bfadgc', LEN('bfadgc')),(140,'ade', LEN('ade')),(140,'degacf', LEN('degacf')),
(141,'dbgfc', LEN('dbgfc')),(141,'cgd', LEN('cgd')),(141,'gcdefa', LEN('gcdefa')),(141,'gdcbfe', LEN('gdcbfe')),
(142,'gafdc', LEN('gafdc')),(142,'fcgbad', LEN('fcgbad')),(142,'afegdc', LEN('afegdc')),(142,'defa', LEN('defa')),
(143,'ebdgacf', LEN('ebdgacf')),(143,'abcged', LEN('abcged')),(143,'fadbeg', LEN('fadbeg')),(143,'gbdefca', LEN('gbdefca')),
(144,'cdea', LEN('cdea')),(144,'ec', LEN('ec')),(144,'ec', LEN('ec')),(144,'ebcgfd', LEN('ebcgfd')),
(145,'gdefba', LEN('gdefba')),(145,'fedc', LEN('fedc')),(145,'bcgea', LEN('bcgea')),(145,'baceg', LEN('baceg')),
(146,'ebac', LEN('ebac')),(146,'abegdc', LEN('abegdc')),(146,'fagbd', LEN('fagbd')),(146,'fbaegdc', LEN('fbaegdc')),
(147,'ad', LEN('ad')),(147,'begafc', LEN('begafc')),(147,'egcba', LEN('egcba')),(147,'ecgab', LEN('ecgab')),
(148,'fdbca', LEN('fdbca')),(148,'cebafd', LEN('cebafd')),(148,'fac', LEN('fac')),(148,'cadbe', LEN('cadbe')),
(149,'faegbdc', LEN('faegbdc')),(149,'bf', LEN('bf')),(149,'adbce', LEN('adbce')),(149,'ecbda', LEN('ecbda')),
(150,'fgcbda', LEN('fgcbda')),(150,'agbcdf', LEN('agbcdf')),(150,'bd', LEN('bd')),(150,'ebdf', LEN('ebdf')),
(151,'ac', LEN('ac')),(151,'cbgead', LEN('cbgead')),(151,'cgfbea', LEN('cgfbea')),(151,'dfbage', LEN('dfbage')),
(152,'ade', LEN('ade')),(152,'abgdec', LEN('abgdec')),(152,'gcdae', LEN('gcdae')),(152,'cdbgfae', LEN('cdbgfae')),
(153,'cgfdbe', LEN('cgfdbe')),(153,'fgacbe', LEN('fgacbe')),(153,'bagcfe', LEN('bagcfe')),(153,'gcfdeb', LEN('gcfdeb')),
(154,'gbe', LEN('gbe')),(154,'agfebcd', LEN('agfebcd')),(154,'ge', LEN('ge')),(154,'abfeg', LEN('abfeg')),
(155,'gecf', LEN('gecf')),(155,'fceg', LEN('fceg')),(155,'bgacfe', LEN('bgacfe')),(155,'gdcbae', LEN('gdcbae')),
(156,'acfge', LEN('acfge')),(156,'cfabde', LEN('cfabde')),(156,'fbdeag', LEN('fbdeag')),(156,'bdag', LEN('bdag')),
(157,'eabc', LEN('eabc')),(157,'decgbaf', LEN('decgbaf')),(157,'afcebdg', LEN('afcebdg')),(157,'gabef', LEN('gabef')),
(158,'cebfag', LEN('cebfag')),(158,'dcgef', LEN('dcgef')),(158,'cgdeab', LEN('cgdeab')),(158,'gcaeb', LEN('gcaeb')),
(159,'adbcef', LEN('adbcef')),(159,'daef', LEN('daef')),(159,'acdbgf', LEN('acdbgf')),(159,'cageb', LEN('cageb')),
(160,'fa', LEN('fa')),(160,'acf', LEN('acf')),(160,'dagebcf', LEN('dagebcf')),(160,'cdbfeg', LEN('cdbfeg')),
(161,'ceagbfd', LEN('ceagbfd')),(161,'bdgfe', LEN('bdgfe')),(161,'gc', LEN('gc')),(161,'cabfedg', LEN('cabfedg')),
(162,'bedgf', LEN('bedgf')),(162,'bdecf', LEN('bdecf')),(162,'egacfb', LEN('egacfb')),(162,'cb', LEN('cb')),
(163,'bda', LEN('bda')),(163,'bda', LEN('bda')),(163,'fead', LEN('fead')),(163,'cdfeb', LEN('cdfeb')),
(164,'gebda', LEN('gebda')),(164,'bgaefc', LEN('bgaefc')),(164,'faegdc', LEN('faegdc')),(164,'adbeg', LEN('adbeg')),
(165,'edgbfc', LEN('edgbfc')),(165,'dbgfce', LEN('dbgfce')),(165,'fgceb', LEN('fgceb')),(165,'caebd', LEN('caebd')),
(166,'gbaec', LEN('gbaec')),(166,'bdaegcf', LEN('bdaegcf')),(166,'bdcfeg', LEN('bdcfeg')),(166,'cfegdb', LEN('cfegdb')),
(167,'bfcagd', LEN('bfcagd')),(167,'beagd', LEN('beagd')),(167,'gadfec', LEN('gadfec')),(167,'cadegf', LEN('cadegf')),
(168,'dcbaf', LEN('dcbaf')),(168,'bedfg', LEN('bedfg')),(168,'aeb', LEN('aeb')),(168,'debcfa', LEN('debcfa')),
(169,'cda', LEN('cda')),(169,'bgace', LEN('bgace')),(169,'dca', LEN('dca')),(169,'dcefg', LEN('dcefg')),
(170,'ecd', LEN('ecd')),(170,'cgfda', LEN('cgfda')),(170,'dbgafe', LEN('dbgafe')),(170,'dbefa', LEN('dbefa')),
(171,'gbac', LEN('gbac')),(171,'fbdga', LEN('fbdga')),(171,'afedgcb', LEN('afedgcb')),(171,'bc', LEN('bc')),
(172,'ebga', LEN('ebga')),(172,'egab', LEN('egab')),(172,'gaeb', LEN('gaeb')),(172,'eg', LEN('eg')),
(173,'abe', LEN('abe')),(173,'bae', LEN('bae')),(173,'cegfabd', LEN('cegfabd')),(173,'bgcfa', LEN('bgcfa')),
(174,'dbfcage', LEN('dbfcage')),(174,'gdafc', LEN('gdafc')),(174,'acfdg', LEN('acfdg')),(174,'ebdfgca', LEN('ebdfgca')),
(175,'cbaged', LEN('cbaged')),(175,'cfgbed', LEN('cfgbed')),(175,'fagc', LEN('fagc')),(175,'aefdc', LEN('aefdc')),
(176,'egabd', LEN('egabd')),(176,'ceagdb', LEN('ceagdb')),(176,'degca', LEN('degca')),(176,'dca', LEN('dca')),
(177,'adgefb', LEN('adgefb')),(177,'eafcb', LEN('eafcb')),(177,'eagbfc', LEN('eagbfc')),(177,'ecbg', LEN('ecbg')),
(178,'efgacb', LEN('efgacb')),(178,'bgdecf', LEN('bgdecf')),(178,'aefcbg', LEN('aefcbg')),(178,'cdfe', LEN('cdfe')),
(179,'dfcabg', LEN('dfcabg')),(179,'fecdba', LEN('fecdba')),(179,'gb', LEN('gb')),(179,'efgadcb', LEN('efgadcb')),
(180,'bgfaced', LEN('bgfaced')),(180,'fcdge', LEN('fcdge')),(180,'gcadef', LEN('gcadef')),(180,'gb', LEN('gb')),
(181,'bdaeg', LEN('bdaeg')),(181,'fa', LEN('fa')),(181,'efa', LEN('efa')),(181,'fa', LEN('fa')),
(182,'gbcedf', LEN('gbcedf')),(182,'gbd', LEN('gbd')),(182,'gbeafc', LEN('gbeafc')),(182,'adebgf', LEN('adebgf')),
(183,'deacf', LEN('deacf')),(183,'afedgb', LEN('afedgb')),(183,'eabdc', LEN('eabdc')),(183,'fbegad', LEN('fbegad')),
(184,'abedg', LEN('abedg')),(184,'df', LEN('df')),(184,'bcaedg', LEN('bcaedg')),(184,'fed', LEN('fed')),
(185,'gcfbe', LEN('gcfbe')),(185,'bae', LEN('bae')),(185,'eba', LEN('eba')),(185,'feadcb', LEN('feadcb')),
(186,'ae', LEN('ae')),(186,'ea', LEN('ea')),(186,'eacgdfb', LEN('eacgdfb')),(186,'cfaedg', LEN('cfaedg')),
(187,'ab', LEN('ab')),(187,'aeb', LEN('aeb')),(187,'fabc', LEN('fabc')),(187,'efabcgd', LEN('efabcgd')),
(188,'dbcfg', LEN('dbcfg')),(188,'gefdb', LEN('gefdb')),(188,'gc', LEN('gc')),(188,'dacbfeg', LEN('dacbfeg')),
(189,'bcgedfa', LEN('bcgedfa')),(189,'efcbd', LEN('efcbd')),(189,'dfgcba', LEN('dfgcba')),(189,'cdefb', LEN('cdefb')),
(190,'fcdegba', LEN('fcdegba')),(190,'fegabd', LEN('fegabd')),(190,'ab', LEN('ab')),(190,'gfcabd', LEN('gfcabd')),
(191,'gfdab', LEN('gfdab')),(191,'cfbe', LEN('cfbe')),(191,'bcegd', LEN('bcegd')),(191,'gfe', LEN('gfe')),
(192,'ca', LEN('ca')),(192,'edcfb', LEN('edcfb')),(192,'dcfeb', LEN('dcfeb')),(192,'cfbeda', LEN('cfbeda')),
(193,'faebd', LEN('faebd')),(193,'dbca', LEN('dbca')),(193,'afecbg', LEN('afecbg')),(193,'fegbca', LEN('fegbca')),
(194,'gdebac', LEN('gdebac')),(194,'ecdba', LEN('ecdba')),(194,'adfb', LEN('adfb')),(194,'bcefad', LEN('bcefad')),
(195,'fdc', LEN('fdc')),(195,'fdebca', LEN('fdebca')),(195,'abedf', LEN('abedf')),(195,'afce', LEN('afce')),
(196,'afbgc', LEN('afbgc')),(196,'edfabg', LEN('edfabg')),(196,'ad', LEN('ad')),(196,'bcadg', LEN('bcadg')),
(197,'acbfd', LEN('acbfd')),(197,'cbgfaed', LEN('cbgfaed')),(197,'facedg', LEN('facedg')),(197,'fcd', LEN('fcd')),
(198,'ecgdf', LEN('ecgdf')),(198,'gfe', LEN('gfe')),(198,'dfceb', LEN('dfceb')),(198,'afcegd', LEN('afcegd')),
(199,'febgc', LEN('febgc')),(199,'ae', LEN('ae')),(199,'ea', LEN('ea')),(199,'bea', LEN('bea')),
(200,'fg', LEN('fg')),(200,'fbcgd', LEN('fbcgd')),(200,'dcgafe', LEN('dcgafe')),(200,'fadgbc', LEN('fadgbc'))


SELECT COUNT(*) FROM @output o INNER JOIN @key_table k ON k.length = o.length AND k.num IN (1,4,7,8)
